/**
 * Cliffco loan officer roster.
 * Source: /compliance/loan-officers.md + /compliance/loan-officer-disclosures.csv (audit 2025-07-23).
 *
 * Each LO drives a /loan-officers/{slug}/ bio page and a Person JSON-LD with
 * sameAs to NMLS Consumer Access — the core E-E-A-T anchor.
 *
 * Photos: every LO with `hasPhoto: true` has /public/team/{slug}.{avif,webp,jpg}
 * generated by scripts/process-repo-headshots.mjs from the /headshots/ folder.
 * LOs without `hasPhoto` show a placeholder until a headshot is provided.
 */

import { COMPANY } from "./company";

export type LoanOfficer = {
  /** URL slug = firstname-lastname-nmlsid */
  slug: string;
  firstName: string;
  lastName: string;
  /** Full display name (preserves middle initials, suffixes, etc.) */
  displayName: string;
  nmls: string;
  title: string;
  /** ISO state codes the LO is licensed in */
  states: readonly string[];
  /** Primary office (branch slug) */
  branchSlug: string;
  /** Languages spoken (LO to confirm) */
  languages?: readonly string[];
  /** External anchors (sameAs) for Person schema */
  links?: {
    linkedin?: string;
    email?: string;
    directPhone?: string;
    calendar?: string;
  };
  /** Specialties — align to the four priority products */
  specialties?: readonly string[];
  /** Long-form bio narrative; populated for leadership wave */
  bio?: string;
  /** Anonymized closing scenarios — only populated when LO confirms */
  scenarios?: readonly { title: string; body: string }[];
  /** Years originating; null if not yet provided */
  yearsExperience?: number;
  yearsAtCliffco?: number;
  /** True if /public/team/{slug}.{avif,webp,jpg} exists */
  hasPhoto?: boolean;
};

export const nmlsConsumerAccessUrl = (nmls: string): string =>
  `https://nmlsconsumeraccess.org/EntityDetails.aspx/INDIVIDUAL/${nmls}`;

export const LOAN_OFFICERS: readonly LoanOfficer[] = [
  // ============================================================
  // WAVE 1 — LEADERSHIP
  // ============================================================
  {
    slug: "christopher-clifford-65234",
    firstName: "Christopher",
    lastName: "Clifford",
    displayName: "Christopher Clifford",
    nmls: "65234",
    title: "President",
    states: ["AK", "AL", "AZ", "CA", "CT", "DC", "DE", "FL", "GA", "IL", "IN", "KS", "KY", "LA", "MD", "MI", "MN", "NC", "NJ", "NM", "NY", "OH", "PA", "SC", "TN", "TX", "VA", "VT", "WA"],
    branchSlug: "uniondale-headquarters",
    specialties: ["Non-QM & Self-Employed", "Reverse Mortgage (HECM)", "DSCR for Investors", "Business Bank Statement", "Jumbo"],
    bio:
      "Christopher Clifford leads Cliffco Mortgage Bankers as President, carrying forward a 36-year " +
      "family-built mortgage operation that's licensed in 32 states. He's licensed in 29 of them personally, " +
      "which means he can pick up the file directly when a complex scenario lands — non-QM, reverse, DSCR, " +
      "business bank statement — with the same hands-on approach Cliffco was founded on.",
    hasPhoto: true,
  },
  {
    slug: "ryan-riddle-1730872",
    firstName: "Ryan",
    lastName: "Riddle",
    displayName: "Ryan Dennis Riddle",
    nmls: "1730872",
    title: "Vice President / COO",
    states: ["AL", "AZ", "CA", "CT", "DC", "DE", "FL", "GA", "IL", "IN", "KS", "KY", "LA", "MD", "MI", "NC", "NJ", "NM", "NY", "OH", "OR", "PA", "SC", "TN", "TX", "VA", "WA"],
    branchSlug: "uniondale-headquarters",
    hasPhoto: true,
  },
  {
    slug: "adam-broder-167538",
    firstName: "Adam",
    lastName: "Broder",
    displayName: "Adam Broder",
    nmls: "167538",
    title: "Vice President",
    states: ["CT", "DE", "FL", "MD", "NJ", "NY", "PA", "TX", "VA"],
    branchSlug: "uniondale-headquarters",
    hasPhoto: true,
  },
  {
    slug: "adam-turkewitz-32900",
    firstName: "Adam",
    lastName: "Turkewitz",
    displayName: "Adam Turkewitz",
    nmls: "32900",
    title: "Senior VP of Sales",
    states: ["AL", "AZ", "CA", "CT", "DC", "FL", "GA", "IL", "IN", "KS", "KY", "LA", "MD", "MN", "NC", "NJ", "NY", "OH", "PA", "SC", "TX", "VA", "VT", "WA"],
    branchSlug: "uniondale-headquarters",
    specialties: ["Non-QM & Self-Employed", "DSCR", "Jumbo"],
    hasPhoto: true,
  },
  {
    slug: "james-chen-17991",
    firstName: "James",
    lastName: "Chen",
    displayName: "James Chen",
    nmls: "17991",
    title: "Senior Vice President of Sales",
    states: ["AZ", "CT", "FL", "GA", "MD", "NC", "NJ", "NY", "OR", "PA", "SC", "TX", "VA"],
    branchSlug: "uniondale-headquarters",
    hasPhoto: true,
  },
  {
    slug: "david-fallarino-673167",
    firstName: "David",
    lastName: "Fallarino",
    displayName: "David Fallarino",
    nmls: "673167",
    title: "Senior Vice President",
    states: ["AZ", "CA", "CT", "FL", "MD", "NC", "NJ", "NY", "PA", "SC", "TX", "VA", "WA"],
    branchSlug: "uniondale-headquarters",
    hasPhoto: true,
  },
  {
    slug: "david-mizrahi-40925",
    firstName: "David",
    lastName: "Mizrahi",
    displayName: "David Mizrahi",
    nmls: "40925",
    title: "Vice President of Sales",
    states: ["CT", "FL", "NJ", "NY", "PA"],
    branchSlug: "uniondale-headquarters",
    hasPhoto: true,
  },

  // ============================================================
  // WAVE 2 — BRANCH MANAGERS
  // ============================================================
  {
    slug: "angelique-street-1146282",
    firstName: "Angelique",
    lastName: "Street",
    displayName: "Angelique Street",
    nmls: "1146282",
    title: "Branch Manager / Loan Officer",
    states: ["NY"],
    branchSlug: "jamaica-ny",
    hasPhoto: true,
  },
  {
    slug: "daphne-feliciano-1227421",
    firstName: "Daphne",
    lastName: "Feliciano",
    displayName: "Daphne Feliciano",
    nmls: "1227421",
    title: "Producing Branch Manager",
    states: ["FL", "MD", "NJ", "PA"],
    branchSlug: "branchburg-nj",
    hasPhoto: true,
  },
  {
    slug: "edward-morais-243926",
    firstName: "Edward",
    lastName: "Morais",
    displayName: "Edward (Eddie) Morais",
    nmls: "243926",
    title: "Branch Manager",
    states: ["FL", "NC", "NJ", "NY", "PA"],
    branchSlug: "branchburg-nj",
    hasPhoto: true,
  },
  {
    slug: "francisco-veras-170512",
    firstName: "Francisco",
    lastName: "Veras",
    displayName: "Francisco Veras",
    nmls: "170512",
    title: "Branch Manager",
    states: ["FL", "NY"],
    branchSlug: "orlando-fl",
    languages: ["English", "Spanish"],
    hasPhoto: true,
  },
  {
    slug: "julian-giaquinto-56473",
    firstName: "Julian",
    lastName: "Giaquinto",
    displayName: "Julian Giaquinto",
    nmls: "56473",
    title: "Branch Manager",
    states: ["AZ", "CA", "CT", "FL", "NC", "NY", "PA", "SC", "TX", "VA"],
    branchSlug: "wantagh-ny",
    hasPhoto: true,
  },

  // ============================================================
  // WAVE 3 — Orlando (FL) bilingual cluster
  // ============================================================
  { slug: "julia-jorge-delcarmen-1555712", firstName: "Julia", lastName: "Jorge-Delcarmen", displayName: "Julia Jorge-Delcarmen", nmls: "1555712", title: "Loan Officer", states: ["FL"], branchSlug: "orlando-fl", languages: ["English", "Spanish"], hasPhoto: true },
  { slug: "keyla-cruz-486181", firstName: "Keyla", lastName: "Cruz", displayName: "Keyla Cruz", nmls: "486181", title: "Loan Officer", states: ["FL"], branchSlug: "orlando-fl", languages: ["English", "Spanish"], hasPhoto: true },
  { slug: "nadia-geyer-castro-2498365", firstName: "Nadia", lastName: "Geyer", displayName: "Nadia Geyer", nmls: "2498365", title: "Loan Officer", states: ["FL"], branchSlug: "orlando-fl", languages: ["English", "Spanish"], hasPhoto: true },
  { slug: "samantha-roach-1956150", firstName: "Samantha", lastName: "Roach", displayName: "Samantha Roach", nmls: "1956150", title: "Loan Officer", states: ["FL"], branchSlug: "orlando-fl", hasPhoto: true },
  { slug: "wenceslao-hernandez-romero-1842661", firstName: "Wenceslao", lastName: "Hernandez Romero", displayName: "Wenceslao Hernandez Romero", nmls: "1842661", title: "Loan Officer", states: ["FL"], branchSlug: "orlando-fl", languages: ["English", "Spanish"], hasPhoto: true },
  { slug: "yaisha-romero-1559680", firstName: "Yaisha", lastName: "Romero", displayName: "Yaisha Romero", nmls: "1559680", title: "Loan Officer", states: ["FL"], branchSlug: "orlando-fl", languages: ["English", "Spanish"], hasPhoto: true },

  // Ft. Lauderdale (FL)
  { slug: "kyle-arabian-1671709", firstName: "Kyle", lastName: "Arabian", displayName: "Kyle Arabian", nmls: "1671709", title: "Branch Manager", states: ["FL"], branchSlug: "fort-lauderdale-fl", hasPhoto: true },

  // Scottsdale (AZ)
  { slug: "steve-wei-1231095", firstName: "Steve", lastName: "Wei", displayName: "Steve Wei", nmls: "1231095", title: "Branch Manager / Vice President of Sales", states: ["AZ", "CA", "TX", "WA"], branchSlug: "scottsdale-az", hasPhoto: true },
  { slug: "katherine-chiang-1600568", firstName: "Katherine", lastName: "Chiang", displayName: "Katherine Chiang", nmls: "1600568", title: "Senior Loan Officer", states: ["AZ", "CO", "TX"], branchSlug: "scottsdale-az", hasPhoto: true },
  { slug: "derek-liu-2578555", firstName: "Derek", lastName: "Liu", displayName: "Derek Liu", nmls: "2578555", title: "Loan Officer", states: ["AZ", "CA", "WA"], branchSlug: "scottsdale-az", hasPhoto: true },
  { slug: "mayra-hernandez-625376", firstName: "Mayra", lastName: "Hernandez", displayName: "Mayra Hernandez", nmls: "625376", title: "Senior Loan Officer", states: ["AZ"], branchSlug: "scottsdale-az", languages: ["English", "Spanish"], hasPhoto: true },

  // Excelsior (MN)
  { slug: "mitchell-patterson-2560483", firstName: "Mitchell", lastName: "Patterson", displayName: "Mitchell Patterson", nmls: "2560483", title: "Loan Officer", states: ["MN", "TX"], branchSlug: "excelsior-mn", hasPhoto: true },

  // Branchburg (NJ)
  { slug: "christian-soto-1173591", firstName: "Christian", lastName: "Soto", displayName: "Christian Soto", nmls: "1173591", title: "Loan Officer", states: ["NJ"], branchSlug: "uniondale-headquarters", languages: ["English", "Spanish"], hasPhoto: true },
  { slug: "gary-johansen-339278", firstName: "Gary", lastName: "Johansen", displayName: "Gary Johansen", nmls: "339278", title: "Regional Sales Manager", states: ["NJ", "NY"], branchSlug: "branchburg-nj", hasPhoto: true },

  // Jamaica (NY) Queens
  { slug: "shahraj-kabir-khan-1209249", firstName: "Shahraj", lastName: "Kabir Khan", displayName: "Shahraj Kabir Khan", nmls: "1209249", title: "Loan Officer", states: ["NY"], branchSlug: "jamaica-ny", hasPhoto: true },

  // Wantagh (NY) Nassau
  { slug: "syed-hasib-1594778", firstName: "Syed", lastName: "Hasib", displayName: "Syed Hasib", nmls: "1594778", title: "Loan Officer", states: ["NY"], branchSlug: "wantagh-ny", hasPhoto: true },

  // Bay Shore (NY) Suffolk — Zambelli cluster
  { slug: "larisa-zambelli-1828224", firstName: "Larisa", lastName: "Zambelli", displayName: "Larisa Ann Zambelli", nmls: "1828224", title: "Loan Officer", states: ["CT", "FL", "NJ", "NY", "PA", "TX"], branchSlug: "bay-shore-ny", hasPhoto: true },
  { slug: "lauren-zambelli-970450", firstName: "Lauren", lastName: "Zambelli", displayName: "Lauren Zambelli", nmls: "970450", title: "Loan Officer", states: ["NY"], branchSlug: "bay-shore-ny", hasPhoto: true },
  { slug: "lisa-zambelli-martorana-13055", firstName: "Lisa", lastName: "Zambelli-Martorana", displayName: "Lisa Zambelli-Martorana", nmls: "13055", title: "Loan Officer", states: ["NY"], branchSlug: "bay-shore-ny", hasPhoto: true },

  // ============================================================
  // WAVE 4 — Uniondale HQ (full roster)
  // ============================================================
  { slug: "anastasios-zervas-2145945", firstName: "Anastasios", lastName: "Zervas", displayName: "Anastasios Zervas", nmls: "2145945", title: "Loan Officer", states: ["NY", "CT", "NJ", "FL"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "brandon-kenney-2144392", firstName: "Brandon", lastName: "Kenney", displayName: "Brandon Kenney", nmls: "2144392", title: "Loan Officer", states: ["CT", "FL", "NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "brendan-mcclarnon-17865", firstName: "Brendan", lastName: "McClarnon", displayName: "Brendan McClarnon", nmls: "17865", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "christian-nguyen-958635", firstName: "Christian", lastName: "Nguyen", displayName: "Christian H. Nguyen", nmls: "958635", title: "Senior Loan Officer", states: ["CA", "CT", "FL", "NJ", "NY", "PA", "TX"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "daniel-ebbecke-1578785", firstName: "Daniel", lastName: "Ebbecke", displayName: "Daniel Ebbecke", nmls: "1578785", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "david-illouz-1584179", firstName: "David", lastName: "Illouz", displayName: "David Illouz", nmls: "1584179", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "donna-hemberger-90881", firstName: "Donna", lastName: "Hemberger", displayName: "Donna Hemberger", nmls: "90881", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "emily-cordeira-1262960", firstName: "Emily", lastName: "Cordeira", displayName: "Emily Cordeira", nmls: "1262960", title: "Loan Officer", states: ["CA", "CT", "FL", "NJ", "NY", "PA", "TX"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "emmanuel-estinvil-66287", firstName: "Emmanuel", lastName: "Estinvil", displayName: "Emmanuel Estinvil", nmls: "66287", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "eric-mueller-1712181", firstName: "Eric", lastName: "Mueller", displayName: "Eric Mueller", nmls: "1712181", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "fabrizio-alosa-2631382", firstName: "Fabrizio", lastName: "Alosa", displayName: "Fabrizio Alosa", nmls: "2631382", title: "Loan Officer", states: ["NJ", "NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "gary-lai-599658", firstName: "Gary", lastName: "Lai", displayName: "Gary Lai", nmls: "599658", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "george-diamantakis-1367963", firstName: "George", lastName: "Diamantakis", displayName: "George Diamantakis", nmls: "1367963", title: "Sales Manager", states: ["CT", "FL", "KY", "NJ", "NY", "PA", "SC", "VA"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "james-perrone-56096", firstName: "James", lastName: "Perrone", displayName: "James P. Perrone", nmls: "56096", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "jeannette-zucker-2572449", firstName: "Jeannette", lastName: "Zucker", displayName: "Jeannette Zucker", nmls: "2572449", title: "Loan Officer", states: ["CA", "CT", "FL", "GA", "NJ", "NY", "PA", "TX"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "johana-amaya-1838913", firstName: "Johana", lastName: "Amaya", displayName: "Johana Amaya", nmls: "1838913", title: "Loan Officer", states: ["NY", "FL", "NJ", "PA"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "joseph-cordeira-1492298", firstName: "Joseph", lastName: "Cordeira", displayName: "Joseph Cordeira", nmls: "1492298", title: "Sales Manager", states: ["CT", "FL", "NJ", "NY", "PA", "TX"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "joshua-borrero-2380321", firstName: "Joshua", lastName: "Borrero", displayName: "Joshua Miguel Borrero", nmls: "2380321", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "joshua-brenner-2030405", firstName: "Joshua", lastName: "Brenner", displayName: "Joshua Brenner", nmls: "2030405", title: "Loan Officer", states: ["CA", "NJ", "NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "justin-hu-2553712", firstName: "Justin", lastName: "Hu", displayName: "Justin Hu", nmls: "2553712", title: "Loan Officer", states: ["NY", "NJ"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "kathie-adler-65780", firstName: "Kathie", lastName: "Adler", displayName: "Kathie Adler", nmls: "65780", title: "Loan Officer", states: ["CA", "FL", "NJ", "NY", "PA", "TX"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "kendra-daniel-1313375", firstName: "Kendra", lastName: "Daniel", displayName: "Kendra Daniel", nmls: "1313375", title: "Loan Officer", states: ["NY", "NJ"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "kevan-scott-1959714", firstName: "Kevan", lastName: "Scott", displayName: "Kevan Scott", nmls: "1959714", title: "Loan Officer", states: ["CT", "NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "leah-silvestri-420488", firstName: "Leah", lastName: "Silvestri", displayName: "Leah Silvestri", nmls: "420488", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "lee-horen-673181", firstName: "Lee", lastName: "Horen", displayName: "Lee Horen", nmls: "673181", title: "Loan Officer", states: ["CT", "FL", "NJ", "NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "lisa-hartman-1730543", firstName: "Lisa", lastName: "Hartman", displayName: "Lisa A. Hartman", nmls: "1730543", title: "Loan Officer", states: ["FL", "NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "logan-levy-2502088", firstName: "Logan", lastName: "Levy", displayName: "Logan Reese Levy", nmls: "2502088", title: "Loan Officer", states: ["AZ", "CA", "FL", "MN", "NC", "NJ", "NY", "PA", "SC", "TN", "VT"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "mario-argenzio-1869384", firstName: "Mario", lastName: "Argenzio", displayName: "Mario Argenzio", nmls: "1869384", title: "Loan Officer", states: ["AZ", "CA", "CO", "CT", "FL", "GA", "MN", "NC", "NJ", "NY", "PA", "SC", "TN", "VA"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "michael-aziz-2801284", firstName: "Michael", lastName: "Aziz", displayName: "Michael Aziz", nmls: "2801284", title: "Loan Officer", states: ["FL"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "michael-bisbee-64809", firstName: "Michael", lastName: "Bisbee", displayName: "Michael Bisbee", nmls: "64809", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "moses-youssef-949405", firstName: "Moses", lastName: "Youssef", displayName: "Moses Youssef", nmls: "949405", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "paul-montesano-4388", firstName: "Paul", lastName: "Montesano", displayName: "Paul J. Montesano", nmls: "4388", title: "Loan Officer", states: ["FL", "MD", "NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "queeny-duong-826674", firstName: "Queeny", lastName: "Duong", displayName: "Queeny Duong", nmls: "826674", title: "Senior Loan Officer", states: ["FL", "NY", "NJ", "PA", "TX"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "rafael-rojas-2082989", firstName: "Rafael", lastName: "Rojas", displayName: "Rafael Rojas", nmls: "2082989", title: "Loan Officer", states: ["CT", "NJ", "NY", "PA", "TX"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "raymond-garcia-2559091", firstName: "Raymond", lastName: "Garcia", displayName: "Raymond Garcia", nmls: "2559091", title: "Loan Officer", states: ["NY", "NJ", "PA"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "renald-appo-53967", firstName: "Renald", lastName: "Appo", displayName: "Renald Appo", nmls: "53967", title: "Loan Officer", states: ["FL", "NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "richard-alvarez-1838273", firstName: "Richard", lastName: "Alvarez", displayName: "Richard Alvarez", nmls: "1838273", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "steven-rivera-1876188", firstName: "Steven", lastName: "Rivera", displayName: "Steven Rivera", nmls: "1876188", title: "Loan Officer", states: ["FL", "NC", "NJ", "NY", "PA"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "tamara-williamson-1933434", firstName: "Tamara", lastName: "Williamson", displayName: "Tamara Williamson", nmls: "1933434", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "thomas-whalen-9167", firstName: "Thomas", lastName: "Whalen", displayName: "Thomas Whalen", nmls: "9167", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "andrea-carver-2074055", firstName: "Andrea", lastName: "Carver", displayName: "Andrea Carver", nmls: "2074055", title: "Loan Officer", states: ["NJ"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "jose-marrero-1962198", firstName: "Jose", lastName: "Marrero", displayName: "Jose Marrero", nmls: "1962198", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
  { slug: "steve-lazo-2636320", firstName: "Steve", lastName: "Lazo", displayName: "Steve Lazo", nmls: "2636320", title: "Loan Officer", states: ["NY"], branchSlug: "uniondale-headquarters", hasPhoto: true },
];

export const loanOfficersByBranch = (branchSlug: string): LoanOfficer[] =>
  LOAN_OFFICERS.filter((lo) => lo.branchSlug === branchSlug);

export const loanOfficersByState = (state: string): LoanOfficer[] =>
  LOAN_OFFICERS.filter((lo) => lo.states.includes(state));

export const loanOfficer = (slug: string): LoanOfficer | undefined =>
  LOAN_OFFICERS.find((lo) => lo.slug === slug);

export const loanOfficerSchemaPerson = (lo: LoanOfficer) => ({
  "@type": "Person",
  name: lo.displayName,
  jobTitle: lo.title,
  worksFor: { "@id": `${COMPANY.legalName}#organization` },
  identifier: {
    "@type": "PropertyValue",
    propertyID: "NMLS",
    value: lo.nmls,
  },
  sameAs: [nmlsConsumerAccessUrl(lo.nmls), lo.links?.linkedin].filter(Boolean),
  knowsLanguage: lo.languages,
  knowsAbout: lo.specialties,
});
