/**
 * Cliffco loan officer roster.
 * Source: /compliance/loan-officers.md + /compliance/loan-officer-disclosures.csv (audit 2025-07-23).
 *
 * Each LO drives a /loan-officers/{slug}/ bio page and a Person JSON-LD with
 * sameAs to NMLS Consumer Access - the core E-E-A-T anchor.
 *
 * Slugs match the vanity URLs on the current Cliffco site (e.g. "skhan", "larisa-zambelli").
 * Photos: every LO with `hasPhoto: true` has /public/team/{slug}.{avif,webp,jpg}
 * generated by scripts/process-repo-headshots.mjs from the /headshots/ folder.
 */

import { COMPANY } from "./company";

export type LoanOfficer = {
  /** Vanity slug matching current site (e.g. "skhan", "larisa-zambelli") */
  slug: string;
  firstName: string;
  lastName: string;
  /** Full display name (preserves middle initials, suffixes, etc.) */
  displayName: string;
  nmls: string;
  title: string;
  /** ISO state codes the LO is licensed in */
  states: readonly string[];
  /** Primary office (branch slug) */
  branchSlug: string;
  /** Languages spoken (LO to confirm) */
  languages?: readonly string[];
  /** External anchors (sameAs) for Person schema */
  links?: {
    linkedin?: string;
    email?: string;
    /** Overrides email as the lead-routing recipient (email stays the displayed contact) */
    leadTo?: string;
    /** Office / direct-dial line */
    directPhone?: string;
    /** Personal cell number */
    cellPhone?: string;
    applyNow?: string;
    calendar?: string;
  };
  /** Specialties - align to the four priority products */
  specialties?: readonly string[];
  /** Featured specialties shown highlighted at the top of the pill list */
  featuredSpecialties?: readonly string[];
  /** Long-form bio narrative */
  bio?: string;
  /** Anonymized closing scenarios - only populated when LO confirms */
  scenarios?: readonly { title: string; body: string }[];
  /** Years originating; null if not yet provided */
  yearsExperience?: number;
  yearsAtCliffco?: number;
  /** True if /public/team/{slug}.{avif,webp,jpg} exists */
  hasPhoto?: boolean;
  /** Personal brand logo shown next to the bio eyebrow on the LO page */
  personalLogo?: string;
  /** Team membership - links LO profile to a team landing page */
  team?: { name: string; slug: string; logoUrl: string; bannerLogoHeight?: string };
  /** Personal blog posts authored by this LO */
  blog?: readonly {
    title: string;
    slug: string;
    description: string;
    image: string;
    section: string;
  }[];
};

export const nmlsConsumerAccessUrl = (nmls: string): string =>
  `https://nmlsconsumeraccess.org/EntityDetails.aspx/INDIVIDUAL/${nmls}`;

export const LOAN_OFFICERS: readonly LoanOfficer[] = [
  // ============================================================
  // LEADERSHIP
  // ============================================================
  {
    slug: "christopher-clifford",
    firstName: "Christopher",
    lastName: "Clifford",
    displayName: "Christopher Clifford",
    nmls: "65234",
    title: "President",
    states: ["AK", "AL", "AZ", "CA", "CT", "DC", "DE", "FL", "GA", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "NC", "NJ", "NM", "NY", "OH", "OR", "PA", "SC", "TN", "TX", "VA", "VT", "WA"],
    branchSlug: "uniondale-headquarters",
    specialties: ["Non-QM & Self-Employed", "Reverse Mortgage (HECM)", "DSCR for Investors", "Business Bank Statement", "Jumbo"],
    bio:
      "Christopher Clifford leads Cliffco Mortgage Bankers as President, carrying forward a 36-year " +
      "family-built mortgage operation that's licensed in 32 states. He's licensed in 29 of them personally, " +
      "which means he can pick up the file directly when a complex scenario lands (Non-QM, reverse, DSCR, " +
      "business bank statement) with the same hands-on approach Cliffco was founded on.",
    links: {
      email: "cclifford@cliffcomortgage.com",
      leadTo: "cliffcorpteam@cliffcomortgage.com",
    },
    hasPhoto: true,
  },
  {
    slug: "ryan-riddle",
    firstName: "Ryan",
    lastName: "Riddle",
    displayName: "Ryan Riddle",
    nmls: "1730872",
    title: "Vice President / COO",
    states: ["AL", "AZ", "CA", "CT", "DC", "DE", "FL", "GA", "IL", "IN", "KS", "KY", "LA", "MD", "MI", "NC", "NJ", "NM", "NY", "OH", "OR", "PA", "SC", "TN", "TX", "VA", "WA"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "rriddle@cliffcomortgage.com",
      directPhone: "516-350-5377",
      cellPhone: "516-661-6658",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=ryanr&workFlowId=33774",
    },
    bio: "Vice President at Cliffco Inc. In the span of little more than five years, he went from an individual with a background in catering to a distinguished partner at one of Long Island's premier mortgage institutions. Over this brief timeframe, he has personally facilitated transactions exceeding $500 million in residential and commercial loans, overseen originations exceeding $1 billion, and successfully maintained the coveted position of holding the #1 market share in the fiercely competitive Long Island market. Beyond his notable achievements in the mortgage realm, Riddle has diversified his portfolio to include Insurance Brokerage, specializing in safeguarding real estate assets. Furthermore, Ryan diversified his portfolio further when he co-founded Tilre Media, a New York media company specializing in marketing, branding, and amplifying personal and business brands, particularly in the real estate sector. The company aims to establish clients' omnipresence and unparalleled influence through innovative strategies. In addition to his entrepreneurial ventures, Riddle is the founder of an Entrepreneurship Conference, a platform that disseminates knowledge and fosters personal growth by uniting thousands under the guidance of distinguished luminaries, including the likes of real estate magnate Grant Cardone. For Ryan, success transcends individual accomplishments; it revolves around forging enduring relationships, nurturing trust, and championing a business ethos that champions mutual prosperity.",
    hasPhoto: true,
  },
  {
    slug: "adam-broder",
    firstName: "Adam",
    lastName: "Broder",
    displayName: "Adam Broder",
    nmls: "167538",
    title: "Vice President",
    states: ["CT", "DE", "FL", "MD", "NJ", "NY", "PA", "TX", "VA"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "abroder@cliffcomortgage.com",
      directPhone: "516-874-6426",
      cellPhone: "516-426-8931",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=adam&workFlowId=33774",
    },
    bio: "Adam Broder is a seasoned professional with over two decades of experience in the mortgage industry. Originally from East Meadow, New York, Adam has been hardworking from a young age. When he was only twenty-two, he was able to purchase his first residential construction property and at twenty-four, he acquired his first building. From then on, Adam knew his true calling. Adam has worked closely with Christopher since 2010 and assisted with the development of Clout Capital and the expansion of Cliffco, Inc as Vice President. Adam has since broken-down barriers by growing, nurturing, and expanding Cliffco and Clout Capital to the Mortgage Banking and Real Estate industries. He is also the owner of a Title Insurance company, Island Estates Abstract. As a Real Estate Investor, Adam has successfully renovated 160 homes, demonstrating a keen eye for real estate opportunities. His experience in Residential Real Estate has allowed him to transition into the Commercial world. In 2018, Adam purchased a 93,000 sqft. building located in Uniondale, New York. This building was vacant at purchase and within 5 years, he was able to fully renovate the property. The building has reached 100% occupancy, including but not limited to medical offices, a State-of-the-Art Conference room, Media Center, Fitness Room, and Cafeteria. With his experience in Ground Up construction and home renovations, Adam has the knowledge and ability to help investors with their projects.",
    hasPhoto: true,
  },
  {
    slug: "james-chen",
    firstName: "James",
    lastName: "Chen",
    displayName: "James Chen",
    nmls: "17991",
    title: "Senior Vice President of Sales",
    states: ["AZ", "CT", "FL", "GA", "MD", "NC", "NJ", "NY", "OR", "PA", "SC", "TX", "VA"],
    branchSlug: "uniondale-headquarters",
    languages: ["English", "Mandarin", "Cantonese", "Taiwanese"],
    links: {
      email: "jchen@cliffcomortgage.com",
      directPhone: "516-874-6572",
      cellPhone: "917-515-8189",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=jchen&workFlowId=33774",
    },
    team: { name: "Team Chen", slug: "team-chen", logoUrl: "/images/team%20logos/Team%20Chen_Stacked_White.png" },
    bio: "As a VP of Cliffco Mortgage Brokers, James both originates loans and manages a team of loan officers and loan officer assistants. His other responsibilities include marketing and brand awareness, recruiting loan officers for Cliffco and his team, and most importantly, helping clients secure the right loan for their unique needs. A veteran Loan Officer since 2003, James enjoyed success early on in the industry as Rookie of the Year for Preferred Empire Mortgage, owned by Douglas Elliman. At DE Capital, JV (Joint Venture) with Wells Fargo, he was their top CRA loan officer for Queens County, NY for many consecutive years, and consistently ranked the Top 5 Loan Officer within the company in volume and units the last four. James next moved to Citizens Bank where he spent eight years, and seven of which, was in the President's Club, ranking #1 for 2021 and 2022. He was also part of Citizens' Circle of Excellence for seven years representing the top 3% of sales within the firm. He earned consistent placement in the Top 10 Loan Officers within the bank, and for his last five years there, was in the Top 3 of Citizens' 500+ loan officers companywide. James also received recognition from AREAA: Asian Real Estate Association, the past five years as a Top 10 Asian American Loan Officer within the Asian community. He is a member of AREAA, and was part of their mortgage task force; plus he's a long-time member of CAREA: Chinese American Real Estate Association, serving on the Board of Directors for 10 of his 20 years. A second generation immigrant from Taiwan, James came to the US when he was 12 and grew up in Flushing, Queens. He earned a Bachelor of Science degree from Queens College, and presently resides in Roslyn, NY. He speaks, reads and writes in Chinese and English, and is married with two teenage children.",
    hasPhoto: true,
  },
  {
    slug: "david-fallarino",
    firstName: "David",
    lastName: "Fallarino",
    displayName: "David Fallarino",
    nmls: "673167",
    title: "Senior Vice President",
    states: ["AZ", "CA", "CT", "FL", "MD", "NC", "NJ", "NY", "PA", "SC", "TX", "VA", "WA"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "dfallarino@cliffcomortgage.com",
      directPhone: "516-350-5345",
      cellPhone: "516-557-4689",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=dfallarino&workFlowId=33774",
    },
    team: { name: "The Fallarino Group", slug: "the-fallarino-group", logoUrl: "/images/team%20logos/The%20Fallarino%20Group_Stacked_White.png" },
    featuredSpecialties: ["High Growth Entrepreneur", "Super Jumbo", "Alt-A"],
    specialties: ["High Growth Entrepreneur","Super Jumbo","Alt-A","Non-QM","DSCR","P&L Loans","Bank Statement","Investment Properties","Renovation Loans","Condo & Co-op","VA Loans","FNMA","Complex Deals","Jumbo & Super Jumbo","Complex Income","Self-Employed","First-Time Buyers"],
    bio: "David Fallarino is one of the country's top-performing mortgage professionals, with over $3 billion in closed loan volume across a 20+ year career. As Senior Vice President at Cliffco Mortgage Bankers, he leads The Fallarino Group, a high-impact origination team specializing in smart, strategic financing solutions for High Growth Entrepreneurs, self-employed professionals, and clients with complex financial profiles. David's experience spans sales and leadership roles at Independent Mortgage Banks, Regional Banks, and National Banks, giving him a 360-degree view of how to navigate even the most challenging loan scenarios. He and his team are known for delivering tailored mortgage strategies, backed by the strength and control of a Direct Lender, with the flexibility to Broker loans when it benefits the client. They offer a full suite of products, from Conventional to Jumbo loan amounts, Conforming loans, A-Paper loans, Non-QM, Alt-A, DSCR, Bridge, Construction Loans, and truly custom-designed solutions others can't match. Raised on Long Island, David spent 15+ years living and working in Manhattan, building relationships and closing deals at some of the largest banks in the country. He now lives back on Long Island with his wife Paula (married 12 years), their 7-year-old twins Ruby and Rome, and their energetic dog, Cash.",
    hasPhoto: true,
    blog: [
      {
        title: "Business Tax Write-Offs Hurt My Mortgage Approval. Now What?",
        slug: "business-tax-write-offs-mortgage-approval",
        description: "Smart tax strategy can make a profitable business look small on a mortgage application. Six ways business owners qualify when the tax return understates the income.",
        image: "/images/DFallarino%20Blog/Tax%20Write%20Offs%20Blog.webp",
        section: "500:1 Blog",
      },
      {
        title: "Complex Income Mortgage Solutions: How Entrepreneurs, Investors, and High-Earning Borrowers Can Get Approved",
        slug: "complex-income-mortgage-solutions",
        description: "Not every qualified borrower has a simple paycheck. How Cliffco and The Fallarino Group help complex income borrowers find the right mortgage structure.",
        image: "/images/DFallarino%20Blog/Complex%20Income%20Blog.jpg",
        section: "500:1 Blog",
      },
      {
        title: "Alt-A vs. A-Paper Loans: Which One Fits the Way You Earn?",
        slug: "alt-a-vs-conventional-mortgage",
        description: "The core distinction between these loan types hinges on income documentation. How to choose the right structure based on the way you earn.",
        image: "/images/DFallarino%20Blog/Alt%20A%20Blog.jpg",
        section: "500:1 Blog",
      },
      {
        title: "Alt-A Loans Make a Comeback: How Entrepreneurs Use Jumbo Alt-A Programs When Big Banks Can't Lend",
        slug: "jumbo-alt-a-loans-entrepreneurs-david-fallarino",
        description: "Modern Alt-A mortgages are re-emerging as structured products for entrepreneurs and high-income professionals who need flexible jumbo financing.",
        image: "/images/DFallarino%20Blog/Jumbo%20Blog.jpg",
        section: "500:1 Blog",
      },
      {
        title: "Freelancers, Entrepreneurs, Investors: We've Got a Mortgage Built Just for You.",
        slug: "mortgages-for-freelancers-entrepreneurs-investors",
        description: "Traditional lenders reject non-traditional earners. Non-QM loans exist for creditworthy borrowers who don't check the standard boxes.",
        image: "/images/DFallarino%20Blog/Freelancers%20Blog.jpg",
        section: "500:1 Blog",
      },
      {
        title: "DSCR Loans Demystified: How Real Estate Investors Can Use Rental Income to Qualify & Scale Their Portfolio",
        slug: "dscr-loans-real-estate-investors",
        description: "DSCR loans flip the script on traditional mortgage underwriting, qualifying you based on rental property cash flow, not your W-2.",
        image: "/images/DFallarino%20Blog/DSCR%20Blog.jpg",
        section: "500:1 Blog",
      },
    ],
  },
  {
    slug: "david-mizrahi",
    firstName: "David",
    lastName: "Mizrahi",
    displayName: "David Mizrahi",
    nmls: "40925",
    title: "Vice President of Sales",
    states: ["CT", "FL", "NJ", "NY", "PA"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "dmizrahi@cliffcomortgage.com",
      directPhone: "516-350-5326",
      cellPhone: "917-597-0870",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=dmizrahi&workFlowId=33774",
    },
    bio: "David began his career in 2001 and has mastered the art of outstanding customer service to both realtors and clients. He is not deterred by challenges (in fact, he embraces them) and refuses to be sidetracked from his ultimate goal: getting a client approved and to their closing as fast as possible. David proudly recalls the time that he assembled the necessary parties, realtors, appraiser, lawyers, etc., and successfully closed a loan, from beginning to end, during a weeklong blizzard. A master of social media, he is one of the most innovative and creative hashtag creators in our company. David has successfully developed relationships with many real estate firms who view him as a treasured resource and a reputable professional with an exemplary work ethic. He is a featured speaker at home-buying seminars and events and is famous for his focused attention to detail and his commitment to providing the ultimate customer experience.",
    hasPhoto: true,
  },
  {
    slug: "moses-youssef",
    firstName: "Moses",
    lastName: "Youssef",
    displayName: "Moses Youssef",
    nmls: "949405",
    title: "Vice President of Sales",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "myoussef@cliffcomortgage.com",
      directPhone: "646-360-8304",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=moses&workFlowId=33774",
    },
    bio: "With over 15 years in mortgage lending and a family legacy spanning more than 30 years in the industry, I've had the privilege of helping more than 1,000 families achieve the dream of homeownership. Licensed in New York, I specialize in guiding first-time homebuyers through the loan process with clarity and confidence. I focus on making home financing simple, stress-free, and educational. Whether it's exploring FHA loan programs, comparing conventional mortgages, or navigating Non-QM options such as bank statement loans, DSCR loans, or P&L programs, I work with clients in all types of unique scenarios, including those facing credit challenges or non-traditional income documentation. Beyond FHA and conventional lending, I also provide support with VA loans and refinancing options, ensuring that each client finds the right path toward long-term financial stability. For me, this business is about more than just closing loans. It's about building lasting relationships and helping families create a secure foundation for their future.",
    hasPhoto: true,
  },

  // ============================================================
  // BRANCH MANAGERS
  // ============================================================
  {
    slug: "angelique-street",
    firstName: "Angelique",
    lastName: "Street",
    displayName: "Angelique Street",
    nmls: "1146282",
    title: "Branch Manager / Loan Officer",
    states: ["NY"],
    branchSlug: "jamaica-ny",
    links: {
      email: "astreet@cliffcomortgage.com",
      directPhone: "315-484-6080",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=astreet&workFlowId=33774",
    },
    bio: "At Cliffco Mortgage Bankers, I take pride in making the mortgage process clear, personalized, and stress-free for every client I serve. Licensed in Central New York, I focus on helping real estate investors, first-time homebuyers, and self-employed borrowers find the right mortgage solutions to fit their goals. From Conventional, FHA, and VA loans to DSCR and bank statement programs, I provide flexible financing options designed to meet a wide range of needs. As both a mortgage professional with investment experience, I understand the strategies that can make your offer stand out, like structuring deals to benefit sellers without raising the purchase price. I'm also well-versed in local grant programs and down payment assistance, helping clients reduce upfront costs while ensuring their monthly obligations align with long-term financial goals. Whether you're buying your first home or looking to expand your investment portfolio, I'm available 24/7 to guide you from pre-approval to closing.",
    hasPhoto: true,
  },
  {
    slug: "daphne-feliciano",
    firstName: "Daphne",
    lastName: "Feliciano",
    displayName: "Daphne Feliciano",
    nmls: "1227421",
    title: "Producing Branch Manager",
    states: ["FL", "MD", "NJ", "PA"],
    branchSlug: "branchburg-nj",
    languages: ["English", "Spanish"],
    links: {
      email: "dfeliciano@cliffcomortgage.com",
      directPhone: "516-930-1059",
      cellPhone: "917-853-5250",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=dfeliciano&workFlowId=33774",
    },
    bio: "With over 20 years of sales and operational experience in mortgage lending, I've dedicated my career to guiding borrowers through home financing with clarity and trust. Licensed in NJ, FL, and PA, I specialize in helping self-employed borrowers, first-time homebuyers, and families overcome credit challenges to achieve the dream of homeownership. As a bilingual Loan Officer (English/Spanish), I've proudly served communities that are often underserved, providing not only mortgage solutions but also education to help clients make confident decisions. My background in Non-QM, DSCR, private, and commercial lending allows me to provide flexible options, even in complex scenarios, whether it's a bank statement loan for entrepreneurs or financing for investors expanding their real estate portfolio. My approach is simple: your goal is my goal.",
    hasPhoto: true,
  },
  {
    slug: "edward-morais",
    firstName: "Edward",
    lastName: "Morais",
    displayName: "Edward (Eddie) Morais",
    nmls: "243926",
    title: "Branch Manager",
    states: ["FL", "NC", "NJ", "NY", "PA"],
    branchSlug: "branchburg-nj",
    languages: ["English", "Spanish"],
    links: {
      email: "emorais@cliffcomortgage.com",
      directPhone: "908-370-1575",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=emorais&workFlowId=33774",
    },
    bio: "With 23 years of experience in the mortgage industry, I've had the privilege of leading top sales teams at some of the nation's largest banks. Specializing in all aspects of home lending, whether it's helping first-time buyers, guiding seasoned investors in building their portfolios, or navigating commercial real estate, I am passionate about making homeownership accessible to all. As the son of immigrants who faced challenges in achieving homeownership, I'm deeply committed to ensuring everyone has the opportunity to build wealth through ownership.",
    hasPhoto: true,
  },
  {
    slug: "julian-giaquinto",
    firstName: "Julian",
    lastName: "Giaquinto",
    displayName: "Julian Giaquinto",
    nmls: "56473",
    title: "Branch Manager",
    states: ["AZ", "CA", "CT", "FL", "NC", "NJ", "NY", "PA", "SC", "TX", "VA"],
    branchSlug: "wantagh-ny",
    links: {
      email: "jgiaquinto@cliffcomortgage.com",
      directPhone: "516-654-9679",
      cellPhone: "516-884-6696",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=jgiaqui&workFlowId=33774",
    },
    team: { name: "Team Giaquinto", slug: "team-giaquinto", logoUrl: "/images/team%20logos/Team%20Giaquinto_Stacked_White.png" },
    specialties: ["Reverse Mortgage"],
    bio: "With over 20 years in the mortgage financing industry, Julian Giaquinto has built a reputation as a dedicated and trusted mortgage banker in New York. As part of Cliffco Mortgage Bankers, Julian offers a wide range of residential loan solutions designed to meet the needs of diverse borrowers, from first-time homebuyers to seasoned real estate investors. His deep knowledge of FHA, conventional, jumbo, and investor loans allows him to tailor mortgage strategies that fit each client's financial goals. Since 2008, Julian has developed a strong specialty in reverse mortgages, guiding seniors and retirees through one of the most important financial decisions of their lives. He believes that when it comes to reverse mortgages, education and personalized guidance are key. In addition to reverse mortgages, Julian also provides innovative financing for clients who may face unique challenges, including self-employed borrowers, no-income check loans, and clients turned down by other banks.",
    hasPhoto: true,
  },
  {
    slug: "kyle-arabian",
    firstName: "Kyle",
    lastName: "Arabian",
    displayName: "Kyle Arabian",
    nmls: "1671709",
    title: "Branch Manager",
    states: ["CT", "FL", "NJ", "NY", "PA"],
    branchSlug: "fort-lauderdale-fl",
    links: {
      email: "karabian@cliffcomortgage.com",
      directPhone: "516-316-3505",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=Karabian&workFlowId=33774",
    },
    bio: "Whether you are a first time home buyer or real estate investor, I will be able to meet all of your financing needs with exceptional service. Every buyers situation is different and I make sure to find the perfect loan that meets each buyers needs and goals. I take pride in the personal touch that I add to my services, all while educating and informing each client about real estate and mortgage financing. I specialize in DSCR loans, Hard money options, and Fix & Flip scenarios. I look forward to being a part of your journey!",
    hasPhoto: true,
  },

  // ============================================================
  // ORLANDO (FL) CLUSTER
  // ============================================================

  // ============================================================
  // SCOTTSDALE (AZ) CLUSTER
  // ============================================================

  // ============================================================
  // EXCELSIOR (MN)
  // ============================================================
  {
    slug: "mitchell-patterson",
    firstName: "Mitchell",
    lastName: "Patterson",
    displayName: "Mitchell Patterson",
    nmls: "2560483",
    title: "Loan Officer",
    states: ["MN", "TX"],
    branchSlug: "excelsior-mn",
    links: {
      email: "mpatterson@cliffcomortgage.com",
      directPhone: "516-202-3307",
      cellPhone: "952-454-6635",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=mpatterson&workFlowId=33774",
    },
    bio: "At Cliffco Mortgage Bankers, I help people find their dream homes with mortgage options they can actually understand. Many of my clients are surprised to discover home financing solutions they never knew existed! What makes working with me different: I explain everything clearly: no confusing terms or surprises. I create loan options that fit your personal situation and goals. I'm here for you long-term, not just until your loan closes. I work with many lenders to find you the best possible rates and terms. Whether you're buying your very first home or starting a new chapter in life, I'll guide you through each step of the process.",
    hasPhoto: true,
  },

  // ============================================================
  // BRANCHBURG (NJ)
  // ============================================================
  {
    slug: "gary-johansen",
    firstName: "Gary",
    lastName: "Johansen",
    displayName: "Gary Johansen",
    nmls: "339278",
    title: "Regional Sales Director",
    states: ["FL", "KY", "NC", "NJ", "PA"],
    branchSlug: "branchburg-nj",
    links: {
      email: "gjohansen@cliffcomortgage.com",
      directPhone: "585-703-8862",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=gjohansen&workFlowId=33774",
    },
    bio: "Gary Johansen is a seasoned mortgage professional with over 30 years of experience helping clients achieve their homeownership and investment goals. Over the course of his career, he has successfully led teams to close more than $15 billion in mortgage transactions, building a reputation as a trusted resource for borrowers and colleagues alike. Specializing in self-employed borrowers, real estate investors, and Non-QM mortgage solutions, Gary provides tailored financing strategies that go beyond traditional lending. From conventional loans and FHA products to bank statement, P&L, and DSCR programs, he helps clients across New Jersey and Florida find mortgage plans that fit their unique financial situations. His background also includes expertise with reverse mortgages and guidance for investors utilizing 1031 exchanges, making him a versatile partner for diverse lending needs.",
    hasPhoto: true,
  },
  {
    slug: "christian-soto",
    firstName: "Christian",
    lastName: "Soto",
    displayName: "Christian Soto",
    nmls: "1173591",
    title: "Loan Officer",
    states: ["NJ"],
    branchSlug: "branchburg-nj",
    languages: ["English", "Spanish"],
    links: {
      email: "csoto@cliffcomortgage.com",
      directPhone: "516-930-1039",
      cellPhone: "718-290-3436",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=csoto&workFlowId=33774",
    },
    bio: "With over 7 years as a Mortgage Loan Officer and over 5 years in retail banking (three of those as a supervisor), I help clients navigate the home financing process with expertise and ease. From first-time buyers to seasoned investors, I deliver personalized lending solutions backed by deep industry knowledge and a commitment to exceptional service.",
    hasPhoto: true,
  },
  {
    slug: "andrea-carver",
    firstName: "Andrea",
    lastName: "Carver",
    displayName: "Andrea Carver",
    nmls: "2074055",
    title: "Loan Officer",
    states: ["NJ"],
    branchSlug: "branchburg-nj",
    links: {
      email: "acarver@cliffcomortgage.com",
      directPhone: "973-868-5473",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=acarver%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    bio: "Hi my name is Andrea Carver, Owner and Principal of A Plus Business Solutions, a professional services firm specializing in tax preparation, bookkeeping, business consulting, and mortgage services. With more than 20 years of experience in financial services, I bring extensive knowledge of the mortgage process, helping clients navigate home purchases, refinancing, and lending solutions with confidence.",
    hasPhoto: true,
  },

  // ============================================================
  // JAMAICA (NY)
  // ============================================================
  {
    slug: "shahraj-khan",
    firstName: "Shahraj",
    lastName: "Kabir Khan",
    displayName: "Shahraj Khan",
    nmls: "1209249",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "jamaica-ny",
    links: {
      email: "skhan@cliffcomortgage.com",
      directPhone: "516-408-7300",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=shahrajk&workFlowId=33774",
    },
    bio: "I have been helping people with their lending needs since 2020. During the start of the Covid 19 pandemic, marked the end of my career in the retail mobile communications business. It was a sad end to 10 exciting years of being in the retail business but also an exciting time to enter a new venture. Shahraj saw the needs of many people during the pandemic to secure loans not only to thrive but also to survive. This was the first step to a fulfilling career in lending. For first time home buyers or seasoned real estate investors, the mortgage process can be an adventure with many moments of discovery. I, known to my clients simply as Shah, have helped them navigate the process and get the deal done. From a simple preapproval all the way until closing day, I act as a guide to the borrower. Always available via email or phone and ready to address any questions that may arise and remedy any complication. I understand the nuances of the mortgage process and if my knowledge is limited on a subject, I can always direct the borrower to the right source or referral partner.",
    hasPhoto: true,
  },

  // ============================================================
  // WANTAGH (NY)
  // ============================================================
  {
    slug: "syed-hasib",
    firstName: "Syed",
    lastName: "Hasib",
    displayName: "Syed Hasib",
    nmls: "1594778",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "wantagh-ny",
    links: {
      email: "shasib@cliffcomortgage.com",
      directPhone: "516-654-9679",
      cellPhone: "516-444-1956",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=shasib&workFlowId=33774",
    },
    team: { name: "Team Giaquinto", slug: "team-giaquinto", logoUrl: "/images/team%20logos/Team%20Giaquinto_Stacked_White.png" },
    bio: "Syed Hasib is a Mortgage Loan Originator serving clients across New York City and Long Island, dedicated to helping individuals and families achieve homeownership with confidence. He specializes in FHA, conventional, and Non-QM loans, with a strong focus on self-employed buyers and first-time homebuyers who need flexible and transparent mortgage solutions. Known for his speed, honesty, and availability, Syed simplifies the mortgage process through clear communication and a commitment to client satisfaction. Whether helping a business owner secure a Non-QM loan, guiding a first-time buyer through FHA programs, or supporting a homeowner looking to refinance, Syed provides a smooth, personalized lending experience.",
    hasPhoto: true,
  },
  {
    slug: "steve-lazo",
    firstName: "Steve",
    lastName: "Lazo",
    displayName: "Steve Lazo",
    nmls: "2636320",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "slazo@cliffcomortgage.com",
      directPhone: "516-350-5352",
      cellPhone: "516-240-0120",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=slazo&workFlowId=33774",
    },
    team: { name: "Team Giaquinto", slug: "team-giaquinto", logoUrl: "/images/team%20logos/Team%20Giaquinto_Stacked_White.png" },
    bio: "With a strong background in New York real estate and a passion for helping clients achieve homeownership, Steve Lazo brings a unique perspective to the mortgage process. His experience as a licensed real estate agent allows him to guide borrowers through every step of purchasing a home with clear communication, quick pre-approvals, and tailored solutions that address real-life challenges. Specializing in first-time homebuyers, Steve helps clients in Uniondale, Hempstead, Long Island, and across New York navigate programs like FHA, Conventional, and DSCR loans. He works closely with borrowers to overcome common hurdles such as credit challenges and down payment concerns, ensuring they have the resources and guidance needed to move forward with confidence.",
    hasPhoto: true,
  },

  // ============================================================
  // BAY SHORE (NY) - ZAMBELLI CLUSTER
  // ============================================================
  {
    slug: "larisa-zambelli",
    firstName: "Larisa",
    lastName: "Zambelli",
    displayName: "Larisa Zambelli",
    nmls: "1828224",
    title: "Loan Officer",
    states: ["CT", "FL", "NJ", "NY", "PA", "SC", "TX"],
    branchSlug: "bay-shore-ny",
    links: {
      email: "zambellil@cliffcomortgage.com",
      directPhone: "516-350-5351",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=larisa&workFlowId=33774",
    },
    team: { name: "Team Zambelli", slug: "team-zambelli", logoUrl: "/images/team%20logos/Team%20Zambelli_White.png", bannerLogoHeight: "h-16" },
    bio: "Larisa Zambelli is a highly accomplished and licensed loan officer from Long Island, NY. With her expertise spanning across multiple states, Larisa has established herself as a trusted professional in the finance industry. Working alongside her mother and sister, who are also loan officers, Larisa forms an unstoppable team that combines years of experience and knowledge. Together, they provide exceptional service to their clients, ensuring that each individual receives personalized attention and tailored solutions to meet their financial needs. Beyond her professional achievements, Larisa is a woman of many talents and interests. She has a passion for DIY projects, constantly seeking new and creative ways to enhance her surroundings. As a former Division One athlete, she brings the same level of dedication and perseverance to her career. Her competitive spirit and commitment to excellence have propelled her to achieve outstanding results for her clients, consistently going above and beyond to ensure their satisfaction.",
    hasPhoto: true,
  },
  {
    slug: "lauren-zambelli",
    firstName: "Lauren",
    lastName: "Zambelli",
    displayName: "Lauren Zambelli",
    nmls: "970450",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "bay-shore-ny",
    links: {
      email: "laurenz@cliffcomortgage.com",
      directPhone: "516-350-5311",
      cellPhone: "631-438-9352",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=laurenz&workFlowId=33774",
    },
    team: { name: "Team Zambelli", slug: "team-zambelli", logoUrl: "/images/team%20logos/Team%20Zambelli_White.png", bannerLogoHeight: "h-16" },
    personalLogo: "/images/team%20logos/Mortgage%20Mama_Black.png",
    bio: "Hi, I'm Lauren Zambelli-Davis, also known as The Mortgage Mama. I'm a Long Island based mortgage loan officer, mom of three, and passionate advocate for helping families build generational wealth through homeownership. What started as a career in mortgages has grown into something so much bigger than I ever imagined. I don't just guide my clients through transactions. I walk alongside them during some of the most important moments of their lives. Whether it's buying a first home, upgrading for a growing family, or creating long-term financial stability, I believe homeownership is one of the most powerful tools we have to build a legacy. As a mom, I understand firsthand how important it is to feel supported, informed, and confident in the decisions you're making for your family. That's why I've built my brand around being approachable, educational, and deeply relationship-driven, so every client feels like they have someone in their corner every step of the way.",
    hasPhoto: true,
  },
  {
    slug: "lisa-zambelli",
    firstName: "Lisa",
    lastName: "Zambelli-Martorana",
    displayName: "Lisa Zambelli",
    nmls: "13055",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "bay-shore-ny",
    links: {
      email: "lzambelli@cliffcomortgage.com",
      directPhone: "516-874-6381",
      cellPhone: "631-871-9857",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=lisaz&workFlowId=33774",
    },
    team: { name: "Team Zambelli", slug: "team-zambelli", logoUrl: "/images/team%20logos/Team%20Zambelli_White.png", bannerLogoHeight: "h-16" },
    bio: "With over 20 years in mortgage lending, Lisa Zambelli has built a reputation as a trusted resource for homebuyers in Nassau and Suffolk County, Long Island. Known for her dedication, responsiveness, and strong track record, Lisa has helped hundreds of families and repeat buyers secure the financing they need to reach their homeownership goals. Alongside her daughters, who are also loan officers, Lisa leads a well-respected team recognized for getting offers accepted in competitive markets and providing personalized solutions that make the process smoother for every client. Lisa specializes in a wide range of programs, including Conventional, FHA, VA, SONYMA, Non-QM, refinances, and family buyouts. She takes the time to educate borrowers, structure loans around their goals, and guide them through important milestones such as optimizing credit, reviewing down payment assistance programs, or navigating family sales. Beyond the closing table, Lisa values her role as a mentor, grandmother, and community supporter.",
    hasPhoto: true,
  },

  // ============================================================
  // UNIONDALE HQ - FULL ROSTER
  // ============================================================
  {
    slug: "anastasios-zervas",
    firstName: "Anastasios",
    lastName: "Zervas",
    displayName: "Anastasios Zervas",
    nmls: "2145945",
    title: "Loan Officer",
    states: ["NY", "CT", "NJ", "FL"],
    branchSlug: "uniondale-headquarters",
    languages: ["English", "Greek"],
    links: {
      email: "azervas@cliffcomortgage.com",
      directPhone: "347-248-8019",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=azervas&workFlowId=33774",
    },
    bio: "As a Mortgage Loan Officer, Certified Mortgage Advisor (CMA) and Certified Divorce Lending Professional (CDLP) my goal is to help people understand how to use mortgage debt to build sustainable, lifelong wealth for them and their families. To do that, I specialize in residential as well as commercial lending with particular emphasis in Non-QM loans and Reverse Mortgages. Non-QM loans pertain to borrowers who cannot be approved through conventional means of qualification like tax returns and income verification channels. Reverse Mortgages can be an excellent tool for homeowners aged 62 and over to improve their cash flow needs. On the personal side, taking unknown, unnecessary chances is not something that I am known for. But taking educated, calculated risks is something that we should all pursue sometime in our lives. Because after all, a ship in port is safe, but that's not what ships are built for.",
    hasPhoto: true,
  },
  {
    slug: "brandon-kenney",
    firstName: "Brandon",
    lastName: "Kenney",
    displayName: "Brandon Kenney",
    nmls: "2144392",
    title: "Loan Officer",
    states: ["CT", "FL", "NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "bkenney@cliffcomortgage.com",
      directPhone: "631-838-1853",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=bkenney&workFlowId=33774",
    },
    team: { name: "The Fallarino Group", slug: "the-fallarino-group", logoUrl: "/images/team%20logos/The%20Fallarino%20Group_Stacked_White.png" },
    featuredSpecialties: ["Renovation Loans", "Investment Properties", "VA Loans"],
    specialties: ["High Growth Entrepreneur","Super Jumbo","Alt-A","Non-QM","DSCR","P&L Loans","Bank Statement","Investment Properties","Renovation Loans","Condo & Co-op","VA Loans","FNMA","Complex Deals","Jumbo & Super Jumbo","Complex Income","Self-Employed","First-Time Buyers"],
    bio: "I am here to answer all of your mortgage and real estate related questions and concerns! When I'm not building my network in the real estate world, I am president of High IQ Basketball, a youth travel basketball program located here on Long Island, NY. I have been coaching youth basketball for over 10 years. I am also COO of the holistic health brand called Sunday Swim. We spread mental health awareness by holding community cold plunges throughout the beaches of Long Island. I love chasing the entrepreneurship dream and believe in impacting the world to make it a better place. I am a part of multiple charity organizations such as Sunrise Day Camp, a camp that is free for children who have cancer and their siblings, and United Way of Long Island, one of the biggest charity organizations in the country.",
    hasPhoto: true,
  },
  {
    slug: "brendan-mcclarnon",
    firstName: "Brendan",
    lastName: "McClarnon",
    displayName: "Brendan McClarnon",
    nmls: "17865",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "bmcclarnon@cliffcomortgage.com",
      directPhone: "631-793-6370",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=brendan&workFlowId=33774",
    },
    bio: "With over 23 years of experience in the banking and mortgage industry, Brendan McClarnon has dedicated his career to helping families achieve their dream of homeownership. A graduate of SUNY Albany Business School, Brendan combines a strong financial background with decades of lending expertise. Over the years, he has successfully guided hundreds of borrowers through first-time homebuyer programs, FHA loans, and refinance options, making the mortgage process clear and approachable. Based in Suffolk and Nassau County, NY, Brendan brings a deep understanding of Long Island's housing market, property values, and community needs. He specializes in self-employed borrower programs, no-income-check mortgages, and hard money loans for investors seeking creative financing solutions.",
    hasPhoto: true,
  },
  {
    slug: "christian-nguyen",
    firstName: "Christian",
    lastName: "Nguyen",
    displayName: "Christian Nguyen",
    nmls: "958635",
    title: "Senior Loan Officer",
    states: ["CT", "FL", "NJ", "NY", "PA", "TX"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "cnguyen@cliffcomortgage.com",
      directPhone: "516-350-5380",
      cellPhone: "201-978-3355",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=cnguyen&workFlowId=33774",
    },
    team: { name: "Team Chen", slug: "team-chen", logoUrl: "/images/team%20logos/Team%20Chen_Stacked_White.png" },
    bio: "Christian H. Nguyen is not just a seasoned mortgage professional; he's a driving force of excellence in the industry. Christian has honed a profound understanding of the ever-evolving mortgage market and mastered the art of navigating its complexities with finesse. What sets Christian apart is not just his expertise but his unwavering commitment to delivering exceptional customer service. He goes above and beyond, providing personalized guidance that caters to each client's unique needs. From meticulously analyzing financial documents to offering insightful loan options, Christian ensures a journey through the mortgage process that is marked by clarity and transparency. During his 8-year tenure at Citizens Bank, he ranked #1 in Customer Satisfaction out of more than 400 bankers. Throughout his illustrious career, Christian has been synonymous with professionalism, integrity, and reliability. Clients trust him implicitly because they know he's not just about securing the loan. He's about helping them achieve their dreams of homeownership.",
    hasPhoto: true,
  },
  {
    slug: "daniel-ebbecke",
    firstName: "Daniel",
    lastName: "Ebbecke",
    displayName: "Daniel Ebbecke",
    nmls: "1578785",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "debbecke@cliffcomortgage.com",
      directPhone: "516-929-9708",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=debbecke%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    bio: "Daniel Ebbecke is a dedicated mortgage loan originator based on Long Island, providing financing solutions for a wide range of clients including real estate investors, first-time buyers, and homeowners seeking refinancing options. He specializes in DSCR loans, fix and flip financing, and commercial and residential mortgages, offering tailored solutions designed to meet unique financial goals. With extensive licensing and a hands-on approach, Daniel works closely with clients and referral partners to ensure a smooth, stress-free lending process. He is known for his availability and ability to deliver quick closings, making him a reliable choice for investors looking to seize time-sensitive opportunities. His knowledge of evolving lending guidelines allows him to provide innovative loan options for self-employed borrowers, investors, and families alike.",
    hasPhoto: true,
  },
  {
    slug: "david-illouz",
    firstName: "David",
    lastName: "Illouz",
    displayName: "David Illouz",
    nmls: "1584179",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "dillouz@cliffcomortgage.com",
      directPhone: "516-874-6414",
      cellPhone: "646-379-3501",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=dillouz&workFlowId=33774",
    },
    bio: "Since 2016, I have built a successful career as a residential mortgage loan officer, helping hundreds of clients achieve their dream of homeownership. With a deep understanding of loan products, market trends, and the intricacies of the mortgage process, I pride myself on delivering personalized, transparent guidance from application to closing. My commitment to clear communication, integrity, and exceptional service has earned me a strong reputation and long-standing relationships with both clients and industry partners. Whether working with first-time homebuyers, seasoned investors, or those refinancing, I focus on making the lending experience as smooth and stress-free as possible.",
    hasPhoto: true,
  },
  {
    slug: "donna-hemberger",
    firstName: "Donna",
    lastName: "Hemberger",
    displayName: "Donna Hemberger",
    nmls: "90881",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "dhemberger@cliffcomortgage.com",
      directPhone: "516-639-3941",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=dhemberger&workFlowId=33774",
    },
    bio: "Homeownership is one of life's biggest milestones, and for over four decades, I've made it my mission to help families reach it. My background spans the entire industry, from underwriting and operations to closing management, which means I know exactly what it takes to get a loan across the finish line. Whether you are buying your first home, refinancing, or building an investment portfolio, I take pride in providing a seamless, supportive experience from start to finish.",
    hasPhoto: true,
  },
  {
    slug: "emily-cordeira",
    firstName: "Emily",
    lastName: "Cordeira",
    displayName: "Emily Cordeira",
    nmls: "1262960",
    title: "Loan Officer",
    states: ["FL", "NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "ecordeira@cliffcomortgage.com",
      directPhone: "516-540-3004",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=ecordeira%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    team: { name: "Team Cordeira", slug: "team-cordeira", logoUrl: "/images/team%20logos/Team%20Cordeira_Stacked_White.png" },
    bio: "Emily Cordeira is a highly trained Mortgage Loan Professional. She has been in the Mortgage industry since 2015 and prides herself on her ability to guide clients on the complete process of buying or refinancing a mortgage loan. With years of experience helping home buyers with their financing needs, her passion has always been putting clients first, listening to their financial goals and providing guidance and support through every step of the loan process. Emily is a Long Island born and raised native out of Massapequa. She enjoys spending time with family, raising her two frenchies, and cooking in Emily's Kitchen.",
    hasPhoto: true,
  },
  {
    slug: "emmanuel-estinvil",
    firstName: "Emmanuel",
    lastName: "Estinvil",
    displayName: "Emmanuel Estinvil",
    nmls: "66287",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "eestinvil@cliffcomortgage.com",
      directPhone: "516-350-5367",
      cellPhone: "516-603-8955",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=emmanuel&workFlowId=33774",
    },
    hasPhoto: true,
  },
  {
    slug: "eric-mueller",
    firstName: "Eric",
    lastName: "Mueller",
    displayName: "Eric Mueller",
    nmls: "1712181",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "emueller@cliffcomortgage.com",
      directPhone: "516-874-6441",
      cellPhone: "516-945-4498",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=emueller&workFlowId=33774",
    },
    bio: "I am a dedicated mortgage professional with extensive experience in mortgage processing and loan origination. Throughout my career, I have developed a strong understanding of the lending process from application through closing, ensuring accuracy, compliance, and a smooth transaction for every client. I specialize in Non-QM, Conventional, FHA, and VA loans, and I am experienced in navigating a wide range of borrower scenarios. I pride myself on my excellent communication skills and my ability to work effectively with borrowers, underwriters, lenders, and industry partners. My goal is always to provide a seamless, efficient, and positive experience while guiding clients confidently through one of the most important financial decisions of their lives.",
    hasPhoto: true,
  },
  {
    slug: "fabrizio-alosa",
    firstName: "Fabrizio",
    lastName: "Alosa",
    displayName: "Fabrizio Alosa",
    nmls: "2631382",
    title: "Loan Officer",
    states: ["NJ", "NY"],
    branchSlug: "uniondale-headquarters",
    languages: ["English", "Spanish"],
    links: {
      email: "falosa@cliffcomortgage.com",
      directPhone: "631-994-5836",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=falosa&workFlowId=33774",
    },
    team: { name: "The Fallarino Group", slug: "the-fallarino-group", logoUrl: "/images/team%20logos/The%20Fallarino%20Group_Stacked_White.png" },
    featuredSpecialties: ["Spanish-Speaking", "First-Time Buyers", "Non-QM", "FHA"],
    specialties: ["High Growth Entrepreneur","Super Jumbo","Alt-A","Non-QM","DSCR","P&L Loans","Bank Statement","Investment Properties","Renovation Loans","Condo & Co-op","VA Loans","FNMA","Complex Deals","Jumbo & Super Jumbo","Complex Income","Self-Employed","First-Time Buyers","Spanish-Speaking"],
    bio: "At the heart of every successful loan experience is a personalized approach, and that's exactly what I deliver. As a bilingual loan officer serving the New York City area, I take the time to understand your unique goals, financial situation, and long-term objectives. My focus is on helping borrowers who may not fit the traditional mold, whether you're self-employed, seeking a jumbo or FHA loan, exploring Non-QM solutions, or refinancing an existing mortgage. I know that no two financial journeys are alike. That's why I work with you to find the right path forward, whether that's through conventional financing, alternative income documentation like bank statements or P&L loans, or tailored refinancing strategies. With guidance in both English and Spanish, I'm dedicated to ensuring that every client feels supported, informed, and confident on their path to homeownership.",
    hasPhoto: true,
  },
  {
    slug: "gary-lai",
    firstName: "Gary",
    lastName: "Lai",
    displayName: "Gary Lai",
    nmls: "599658",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "glai@cliffcomortgage.com",
      directPhone: "516-874-6497",
      cellPhone: "917-675-0745",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=glai%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    bio: "Gary Lai is a seasoned mortgage loan officer with Cliffco Mortgage Bankers, bringing over 20 years of lending experience to clients across New York City and Northern New Jersey. Starting his career in 2003 as a loan assistant, Gary steadily grew into a top-producing role, known for providing personalized mortgage solutions that meet the needs of today's diverse borrowers. He works with a wide range of clients, from first-time homebuyers to experienced real estate investors, offering financing tailored to conventional, jumbo, condo, and co-op properties. Gary is especially skilled at guiding self-employed borrowers through flexible programs such as bank statement, P&L, and alternative documentation loans. In addition to serving his clients, Gary has built strong partnerships with leading real estate teams throughout NYC and Northern NJ. He has also served as the AREAA National Mortgage Chair and AREAA National Secretary, reflecting his ongoing commitment to expanding access to homeownership in the community.",
    hasPhoto: true,
  },
  {
    slug: "george-diamantakis",
    firstName: "George",
    lastName: "Diamantakis",
    displayName: "George Diamantakis",
    nmls: "1367963",
    title: "Sales Manager",
    states: ["CT", "FL", "KY", "NJ", "NY", "PA", "SC", "VA"],
    branchSlug: "uniondale-headquarters",
    languages: ["English", "Greek"],
    links: {
      email: "george@cliffcomortgage.com",
      directPhone: "516-874-6394",
      cellPhone: "516-860-9978",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=george&workFlowId=33774",
    },
    bio: "Hello everyone! My name is George and I am a Senior Loan Officer at Cliffco Mortgage Bankers. My goal is to show my expertise in customer service through every transaction I am involved in. I treat every client as if they are family. In life, the gift of giving is one of the most gratifying things anyone can do. My line of work allows me to extend the opportunity to not only help a client own a home but help plan their future by making smart financial decisions from the moment their trust is put in my hands. Being thoroughly qualified from the beginning is my advice as it makes us aware of how smooth our transaction will be, and we only strive for the best! I look forward to working with you if you are a first time home buyer, if you are self-employed and/or need alternative financing in any form. We have many options between purchase and refinance transactions. I will work on anything you throw at me and find the right product for every scenario. I love working at Cliffco Mortgage because I feel like I'm part of the family and that's how I run my business. Whether you are an actual family member of mine, friend or a new client, you will get the experience of being part of my family here.",
    hasPhoto: true,
  },
  {
    slug: "james-perrone",
    firstName: "James",
    lastName: "Perrone",
    displayName: "James Perrone",
    nmls: "56096",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "jperrone@cliffcomortgage.com",
      directPhone: "516-350-5334",
      cellPhone: "516-967-3593",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=jim&workFlowId=33774",
    },
    bio: "With over 30 years of mortgage experience, James Perrone serves borrowers throughout Westchester, New York City, and Long Island. He specializes in helping those who may not fit the traditional lending mold, including self-employed buyers, small business owners, and clients with credit challenges. James is known for finding flexible loan programs that match real-world financial situations. James frequently works with clients seeking FHA loans for affordable homeownership and reverse mortgages for homeowners 62+ who want to access their home equity in retirement. Whether you are purchasing your first home, refinancing, or exploring retirement solutions, James provides practical guidance with a proven track record of success.",
    hasPhoto: true,
  },
  {
    slug: "jeannette-zucker",
    firstName: "Jeannette",
    lastName: "Zucker",
    displayName: "Jeannette Zucker",
    nmls: "2572449",
    title: "Loan Officer",
    states: ["CA", "CT", "FL", "GA", "NJ", "NY", "PA", "TX"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "jzucker@cliffcomortgage.com",
      directPhone: "516-929-9702",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=jzucker&workFlowId=33774",
    },
    team: { name: "Team Chen", slug: "team-chen", logoUrl: "/images/team%20logos/Team%20Chen_Stacked_White.png" },
    bio: "Jeannette N. Zucker's professional journey is a testament to her multifaceted expertise and unwavering commitment to making a meaningful impact. Beginning her career as a physical therapist, she earned her Doctorate in Physical Therapy from New York University. She spent 16 enriching years at Memorial Sloan Kettering where she honed her skills in leadership, operations, and financial management, contributing significantly to the institution's mission of excellence in cancer care. Driven by a desire to broaden her horizons, Jeannette achieved her MBA from Quantic School of Business and Technology. She also assumed the role of Executive Director for the National Lymphedema Network, a position she held for six impactful years, spearheading initiatives and advocating for patients' rights. Now embarking on an exciting new chapter in the Financial Sector, Jeannette brings her wealth of experience and expertise to the dynamic world of mortgage banking. Her unique blend of healthcare and financial backgrounds equips her to navigate complex financial scenarios with empathy and precision, ensuring that each client receives tailored solutions and exceptional service.",
    hasPhoto: true,
  },
  {
    slug: "johana-amaya",
    firstName: "Johana",
    lastName: "Amaya",
    displayName: "Johana Amaya",
    nmls: "1838913",
    title: "Loan Officer",
    states: ["NY", "FL", "NJ", "PA"],
    branchSlug: "uniondale-headquarters",
    languages: ["English", "Spanish"],
    links: {
      email: "jamaya@cliffcomortgage.com",
      directPhone: "516-508-6258",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=jamaya&workFlowId=33774",
    },
    bio: "Mortgage lending is more than selling loans. It's about helping people achieve their home ownership goals. Whether that's helping them reach a better financial position or connecting them to the home of their dreams, it's about guiding them to the finish line. My industry experience has taught me to take the time to understand my customers: What's their story? How can I help them in their pursuit of a home? When I see my customers as real people with real goals, needs, and dreams, I get to match them with the best loan product and create a truly seamless lending experience. Everyone has a story to tell. What they need is a Loan Originator who will listen, customize a loan to meet their needs, and guide them every step of the way. I look forward to working with you!",
    hasPhoto: true,
  },
  {
    slug: "joseph-cordeira",
    firstName: "Joseph",
    lastName: "Cordeira",
    displayName: "Joseph Cordeira",
    nmls: "1492298",
    title: "Sales Manager",
    states: ["CT", "FL", "NJ", "NY", "PA", "TX"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "jcordeira@cliffcomortgage.com",
      directPhone: "516-996-9070",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=jcordeira&workFlowId=33774",
    },
    team: { name: "Team Cordeira", slug: "team-cordeira", logoUrl: "/images/team%20logos/Team%20Cordeira_Stacked_White.png" },
    bio: "Joseph Cordeira is a highly trained Mortgage Loan Professional. He has been in the Mortgage industry since 2015 and prides himself on his ability to guide his clients on the complete process of buying or refinancing a mortgage loan. He is well versed in today's Real Estate technology, which gives him an advantage for the clients he services. Whether you are buying, selling, or investing into Real Estate, Joseph Cordeira will be able to provide exceptional service that will give you the competitive edge. \"My clients are my number one priority over anything else. My goal is to make a long-lasting relationship and bond with my clients so I can help their friends and family with the best service possible while providing the lowest interest rate for the best cost.\" Joseph graduated from Massapequa High School and received a full scholarship to play lacrosse at the New York Institute of Technology where he went on to study Business Management.",
    hasPhoto: true,
  },
  {
    slug: "joshua-borrero",
    firstName: "Joshua",
    lastName: "Borrero",
    displayName: "Joshua Borrero",
    nmls: "2380321",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    languages: ["English", "Spanish"],
    links: {
      email: "jborrero@cliffcomortgage.com",
      directPhone: "516-408-7300",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=jborrero&workFlowId=33774",
    },
    bio: "Joshua Borrero is a dedicated Mortgage Loan Originator at Cliffco Mortgage Bankers in New York, specializing in FHA loans, first-time homebuyers, and fast closings for borrowers facing credit or down payment challenges. In just three years, Joshua has helped close over $100 million in mortgage volume, showcasing his strong financial insight and relentless work ethic. Beginning his career as a Loan Officer Assistant, Joshua quickly advanced by mastering the nuances of mortgage banking and developing a client-first approach. Today, he provides tailored financing solutions for a wide range of borrowers, including self-employed clients, FHA buyers, and those exploring conventional and refinance options. Joshua is committed to ensuring his clients understand their mortgage choices, guiding them with clarity and personalized service.",
    hasPhoto: true,
  },
  {
    slug: "joshua-brenner",
    firstName: "Joshua",
    lastName: "Brenner",
    displayName: "Joshua Brenner",
    nmls: "2030405",
    title: "Loan Officer",
    states: ["CA", "NJ", "NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "jbrenner@cliffcomortgage.com",
      directPhone: "845-559-8390",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=jbrenner&workFlowId=33774",
    },
    bio: "Joshua Brenner began his real estate career in 2016 at a small investment bank where he arranged financing for commercial transactions. In 2020 he began working with families buying homes and investors creating portfolios, and he continues to serve those same clients today at Cliffco Mortgage Bankers. He has combined his deep knowledge of real estate and customer service to craft a loan process that removes doubt and minimizes stress for clients and realtor partners. Josh gets his clients to the closing table on time and without surprises.",
    hasPhoto: true,
  },
  {
    slug: "justin-hu",
    firstName: "Justin",
    lastName: "Hu",
    displayName: "Justin Hu",
    nmls: "2553712",
    title: "Loan Officer",
    states: ["NY", "NJ"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "jhu@cliffcomortgage.com",
      directPhone: "516-874-6507",
      cellPhone: "516-800-2870",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=jhu%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    hasPhoto: true,
  },
  {
    slug: "kathie-adler",
    firstName: "Kathie",
    lastName: "Adler",
    displayName: "Kathie Adler",
    nmls: "65780",
    title: "Loan Officer",
    states: ["CA", "FL", "NJ", "NY", "TX"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "kadler@cliffcomortgage.com",
      directPhone: "516-930-1062",
      cellPhone: "631-804-9044",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=kadler%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    team: { name: "Team Giaquinto", slug: "team-giaquinto", logoUrl: "/images/team%20logos/Team%20Giaquinto_Stacked_White.png" },
    specialties: ["Reverse Mortgage"],
    bio: "An industry professional for over 20 years (starting in 2003), Kathie offers experience, expertise, and unparalleled customer service. During the buying process, you need a trusted resource with the ability to walk a homebuyer through the process with ease. And with Reverse Mortgages, you need an expert who can teach as well as assist a senior client with their mortgage. Kathie's expertise includes various mortgage products such as: FHA, VA, Conventional, Commercial, Non-QM (bank statement loans), and Reverse Mortgages to name a few. Kathie always puts her borrowers at ease especially when complicated situations arise. Respect and understanding are essential when doing a mortgage. And that's what you'll get with Kathie Adler.",
    hasPhoto: true,
  },
  {
    slug: "kendra-daniel",
    firstName: "Kendra",
    lastName: "Daniel",
    displayName: "Kendra Daniel",
    nmls: "1313375",
    title: "Loan Officer",
    states: ["NY", "NJ"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "kdaniel@cliffcomortgage.com",
      directPhone: "347-737-2952",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=kdaniel%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    bio: "Kendra has worked in the mortgage industry for the past twenty two years. She graduated with a Bachelor's Degree in Finance and earned a Masters Degree in Economics. Kendra found her passion helping first time home buyers when she first started her career as a Mortgage Consultant in 1999. She is a tremendous advocate for her clients and always prioritizes their interests. Kendra has served as a Senior Loan Officer for Cliffco Mortgage Bankers since 2012. Whether you are looking to purchase your first home, refinance your current home, or add to your portfolio of real estate as an investor, Kendra is committed to helping you achieve your home ownership dreams.",
    hasPhoto: true,
  },
  {
    slug: "kevan-scott",
    firstName: "Kevan",
    lastName: "Scott",
    displayName: "Kevan Scott",
    nmls: "1959714",
    title: "Loan Officer",
    states: ["CT", "NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "kscott@cliffcomortgage.com",
      directPhone: "631-704-0552",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=kscott%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    team: { name: "The Fallarino Group", slug: "the-fallarino-group", logoUrl: "/images/team%20logos/The%20Fallarino%20Group_Stacked_White.png" },
    featuredSpecialties: ["DSCR", "P&L Loans", "Real Estate Investors"],
    specialties: ["High Growth Entrepreneur","Super Jumbo","Alt-A","Non-QM","DSCR","P&L Loans","Bank Statement","Investment Properties","Renovation Loans","Condo & Co-op","VA Loans","FNMA","Complex Deals","Jumbo & Super Jumbo","Complex Income","Self-Employed","First-Time Buyers"],
    bio: "Kevan Scott is a Mortgage Loan Originator with Cliffco Mortgage Bankers, proudly serving clients throughout Suffolk County, Nassau County, Queens, and Brooklyn, NY. He specializes in jumbo loans, Non-QM mortgage products, and investment property financing, with a focus on helping business owners and self-employed borrowers access flexible lending solutions that fit their unique financial profiles. With extensive experience in both traditional and alternative mortgage programs (including bank statement, P&L, and other Non-QM loan options), Kevan helps clients overcome income documentation challenges and structure loans that align with their goals. His deep product knowledge, creativity, and commitment to timely closings make him a valuable resource for first-time homebuyers, investors, and high-net-worth borrowers seeking tailored financing strategies.",
    hasPhoto: true,
  },
  {
    slug: "lee-horen",
    firstName: "Lee",
    lastName: "Horen",
    displayName: "Lee Horen",
    nmls: "673181",
    title: "Loan Officer",
    states: ["CT", "FL", "NJ", "NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "lhoren@cliffcomortgage.com",
      directPhone: "516-930-1042",
      cellPhone: "917-880-2102",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=lhoren&workFlowId=33774",
    },
    team: { name: "The Fallarino Group", slug: "the-fallarino-group", logoUrl: "/images/team%20logos/The%20Fallarino%20Group_Stacked_White.png" },
    featuredSpecialties: ["Complex Deals", "Jumbo & Super Jumbo", "Complex Income"],
    specialties: ["High Growth Entrepreneur","Super Jumbo","Alt-A","Non-QM","DSCR","P&L Loans","Bank Statement","Investment Properties","Renovation Loans","Condo & Co-op","VA Loans","FNMA","Complex Deals","Jumbo & Super Jumbo","Complex Income","Self-Employed","First-Time Buyers"],
    bio: "With more than 25 years in the residential mortgage business, Lee Horen has built a reputation for helping clients secure financing in even the most complex scenarios. Serving New York City, Long Island, Westchester, Northern New Jersey, and Florida, Lee specializes in jumbo and super jumbo mortgage loans, with a strong focus on serving self-employed borrowers. Nearly 70% of his clients are entrepreneurs, business owners, or professionals with unique income structures, making Lee highly experienced in addressing complicated tax returns, cash flow analysis, and debt restructuring. Lee's approach is rooted in problem-solving and personalized service. Whether you are purchasing a luxury property requiring a super jumbo mortgage over $5M, refinancing to optimize cash flow, or exploring flexible loan programs designed for self-employed borrowers, Lee takes the time to structure financing that aligns with each client's goals.",
    hasPhoto: true,
  },
  {
    slug: "lisa-hartman",
    firstName: "Lisa",
    lastName: "Hartman",
    displayName: "Lisa Hartman",
    nmls: "1730543",
    title: "Loan Officer",
    states: ["FL", "NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "lhartman@cliffcomortgage.com",
      directPhone: "516-695-9060",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=lisab&workFlowId=33774",
    },
    bio: "Lisa has been in the mortgage industry for many years and has helped countless clients achieve their dream of homeownership. She prides herself in that \"individual client experience\" as each client's situation is different and unique. Providing that one on one time to truly get to know them and their own personal story has allowed for many happy clients at the closing table. She makes herself available day or night, so that the client's anxiousness in the mortgage process is eased. Whether that be through phone calls, meetings in person, texts, or virtual meetings, Lisa will provide answers and assist any way she can. Being dedicated to her job as a Loan Officer as well as being dedicated to all her clients has made for many dreams come true for clients! Lisa truly cares about all her clients, and will ensure she will do all she can so that the experience from pre-approval straight to the closing table is a happy one!",
    hasPhoto: true,
  },
  {
    slug: "logan-levy",
    firstName: "Logan",
    lastName: "Levy",
    displayName: "Logan Levy",
    nmls: "2502088",
    title: "Loan Officer",
    states: ["AZ", "CA", "FL", "MN", "NC", "NJ", "NY", "PA", "TN", "VT"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "llevy@cliffcomortgage.com",
      directPhone: "516-559-9745",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=llevy&workFlowId=33774",
    },
    bio: "As a Mortgage Loan Officer licensed in New York, New Jersey, Florida, Pennsylvania, and more, I specialize in helping both first-time homebuyers and real estate investors find the right financing solutions. From FHA and Conventional loans to Non-QM products such as bank statement loans, I provide options designed for self-employed borrowers and those with unique income or credit situations. I also offer guidance on reverse mortgages and down payment assistance programs, giving clients the tools they need to achieve their goals. My approach is simple: I work non-stop to make the mortgage process smooth, transparent, and stress-free. Whether you're purchasing your first home, refinancing, or building an investment portfolio, I'll help match you with loan programs that align with your financial needs and long-term plans.",
    hasPhoto: true,
  },
  {
    slug: "mario-argenzio",
    firstName: "Mario",
    lastName: "Argenzio",
    displayName: "Mario Argenzio",
    nmls: "1869384",
    title: "Loan Officer",
    states: ["AZ", "CA", "CO", "CT", "FL", "GA", "MD", "MN", "NC", "NJ", "NY", "PA", "SC", "TN", "VA"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "margenzio@cliffcomortgage.com",
      directPhone: "516-350-5358",
      cellPhone: "917-716-4127",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=mario&workFlowId=33774",
    },
    bio: "I have been a seasoned professional in the mortgage industry for over 20 years. I bring knowledge, experience and innovative products with superior service to Cliffco Mortgage Bankers. I am a native New Yorker born and raised in Queens NY and a graduate of St John's University. I am married for over 15 years and I am raising two beautiful teenage daughters with my wife in Whitestone NY. I am a diligent worker and I am determined to make your dreams come true by getting you the mortgage that is right for you.",
    hasPhoto: true,
  },
  {
    slug: "michael-aziz",
    firstName: "Michael",
    lastName: "Aziz",
    displayName: "Michael Aziz",
    nmls: "2801284",
    title: "Loan Officer",
    states: ["FL"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "maziz@cliffcomortgage.com",
      directPhone: "347-848-2473",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=Maziz&workFlowId=33774",
    },
    bio: "Michael Aziz is an experienced Mortgage Loan Originator serving New York and Florida, with a strong foundation as a real estate broker, owner, and investor. His hands-on experience in real estate allows him to guide clients through the financing process with a strategic, investor-minded approach. Michael focuses on 1-4 family properties and DSCR loan solutions, supporting both homeowners and real estate investors in achieving their goals.",
    hasPhoto: true,
  },
  {
    slug: "michael-bisbee",
    firstName: "Michael",
    lastName: "Bisbee",
    displayName: "Michael Bisbee",
    nmls: "64809",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "mbisbee@cliffcomortgage.com",
      directPhone: "516-761-1155",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=mbisbee&workFlowId=33774",
    },
    bio: "Michael Bisbee has been originating residential mortgage loans since 1986 and is uniquely qualified having run his own mortgage company successfully for over 25 years and earning the trust of hundreds of applicants by putting his borrowers first and being a careful listener. Michael's many years in the mortgage industry provides his clients with extensive experience in all aspects of a real estate transaction including appraisal, title and legal matters. He enjoys educating his applicants on the process and offering support every step of the way, welcoming calls from his customers whether it is day or night.",
    hasPhoto: true,
  },
  {
    slug: "paul-montesano",
    firstName: "Paul",
    lastName: "Montesano",
    displayName: "Paul Montesano",
    nmls: "4388",
    title: "Loan Officer",
    states: ["FL", "MD", "NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "paul@cliffcomortgage.com",
      directPhone: "516-350-5375",
      cellPhone: "516-859-7747",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=paul&workFlowId=33774",
    },
    bio: "With over 23 years of mortgage lending experience, I've guided hundreds of clients across Nassau and Suffolk Counties and beyond in reaching their homeownership and investment goals. Whether you're a first-time homebuyer, a real estate investor, or looking to refinance, I take pride in making the mortgage process clear, stress-free, and tailored to your financial needs. As a dedicated Mortgage Loan Officer, I provide personalized support from pre-approval through closing. My focus is on educating clients about their options so they can make confident decisions that align with both short- and long-term goals. I understand that every borrower's situation is unique, and I specialize in helping clients overcome down payment hurdles, credit challenges, and complex financial scenarios. No matter your background, income type, or credit profile, I am committed to helping you find the right financing solution and delivering a fast closing so you can move forward with confidence.",
    hasPhoto: true,
  },
  {
    slug: "queeny-duong",
    firstName: "Queeny",
    lastName: "Duong",
    displayName: "Queeny Duong",
    nmls: "826674",
    title: "Senior Loan Officer",
    states: ["FL", "NY", "NJ", "PA", "TX"],
    branchSlug: "uniondale-headquarters",
    languages: ["English", "Cantonese"],
    links: {
      email: "qduong@cliffcomortgage.com",
      directPhone: "516-874-6561",
      cellPhone: "917-284-0865",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=qduong&workFlowId=33774",
    },
    bio: "Queeny has always dedicated herself to providing exceptional service and building relationships, whether working in hospitality management, or helping people secure the best mortgage for their needs. A seasoned veteran of the mortgage industry since 2006, and a Senior Loan Officer at Cliffco, she has earned a stellar reputation as well as prominent awards for her excellence. Most recently these include being recognized as a Presidents Club recipient for three consecutive years (2020, 2021, 2022) at her previous firm, Citizens Bank. In her current role at Cliffco, Queeny is responsible for originating mortgage loans for residential properties, condos, co-ops, one-to-four-family homes, as well as mixed-use properties up to 12 units. She is extremely detail oriented, creative and communicative, and performs a thorough review of each client's financials, to determine their qualification and assure placement with a favorable product and rate. Originally from Brooklyn, NY, Queeny received a Bachelor degree in Finance and Investment from Baruch College. Queeny speaks English and Cantonese fluently and is a member of the Asian Real Estate Association (AREAA), Brooklyn chapter.",
    hasPhoto: true,
  },
  {
    slug: "rafael-rojas",
    firstName: "Rafael",
    lastName: "Rojas",
    displayName: "Rafael Rojas",
    nmls: "2082989",
    title: "Loan Officer",
    states: ["CO", "CT", "NJ", "NY", "PA", "TX"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "rrojas@cliffcomortgage.com",
      directPhone: "347-723-8857",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=rrojas&workFlowId=33774",
    },
    bio: "As a Mortgage Loan Originator with over 19 years of sales experience, I bring a strong commitment to building lasting client relationships through trust, communication, and personalized service. My experience, combined with a genuine passion for helping others, allows me to guide clients confidently through important financial decisions. I strive to be a resource for clients by answering questions, addressing concerns, and providing clarity before they commit to any major financial milestone. I understand the value of having a strong support system, especially during the home financing process. My goal is to be a dependable part of that support system for every client I serve. Outside of work, I enjoy spending time with my family and exploring the world. I bring that same appreciation for relationships, trust, and connection into the way I work with my clients.",
    hasPhoto: true,
  },
  {
    slug: "raymond-garcia",
    firstName: "Raymond",
    lastName: "Garcia",
    displayName: "Raymond Garcia",
    nmls: "2559091",
    title: "Loan Officer",
    states: ["NY", "NJ", "PA"],
    branchSlug: "uniondale-headquarters",
    languages: ["English", "Spanish"],
    links: {
      email: "rgarcia@cliffcomortgage.com",
      directPhone: "631-860-8582",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=rgarcia&workFlowId=33774",
    },
    bio: "With years of experience in mortgage lending, Raymond Garcia specializes in helping self-employed borrowers and real estate investors navigate financing with clarity and confidence. Serving clients across the Tri-State area, he is known for delivering personalized solutions that support unique income situations and complex financial goals. From first-time buyers to seasoned investors, Raymond ensures that each client receives clear guidance and a smooth process from application to closing. Raymond's work extends beyond traditional lending. He assists entrepreneurs, business owners, and investors in securing financing for rental portfolios, fix and flip projects, and private lending options. As a bilingual loan officer (English/Spanish) and investment advisor, he is dedicated to supporting underserved communities and empowering clients to build wealth through real estate.",
    hasPhoto: true,
  },
  {
    slug: "renald-appo",
    firstName: "Renald",
    lastName: "Appo",
    displayName: "Renald Appo",
    nmls: "53967",
    title: "Loan Officer",
    states: ["FL", "NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "rappo@cliffcomortgage.com",
      directPhone: "516-350-5349",
      cellPhone: "516-395-5945",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=rappo&workFlowId=33774",
    },
    bio: "I am a dedicated mortgage loan officer who puts client needs at the center of every decision. Whether someone is buying their first home, upgrading to their dream property, or refinancing to build long-term stability, I take the time to understand their goals and guide them toward the loan program that fits their unique situation. Helping people achieve homeownership is my passion. I look forward to assisting you on your journey to owning a home.",
    hasPhoto: true,
  },
  {
    slug: "steven-rivera",
    firstName: "Steven",
    lastName: "Rivera",
    displayName: "Steven Rivera",
    nmls: "1876188",
    title: "Loan Officer",
    states: ["FL", "NC", "NJ", "NY", "PA"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "srivera@cliffcomortgage.com",
      directPhone: "631-848-9930",
      applyNow: "https://cliffco.mymortgage-online.com/loan-app/?siteId=3232086255&lar=strivera&workFlowId=33774",
    },
    bio: "Steven, a seasoned professional in the real estate industry, has devoted his extensive knowledge and expertise to construct a comprehensive ecosystem that spans every facet of real estate. With a distinguished career marked by a commitment to excellence, Steven has become a trusted authority in guiding individuals towards achieving their homeownership dreams. His genuine passion lies in empowering others to build a lifestyle centered around the things that truly matter most. As an adept mortgage loan officer, Steven is dedicated to demystifying the complexities of the mortgage process, ensuring that his clients not only secure the keys to their dream homes but also embark on a journey of financial well-being. He prides himself on providing personalized guidance, tailoring each mortgage solution to meet the unique needs and aspirations of his clients.",
    hasPhoto: true,
  },
  {
    slug: "tamara-williamson",
    firstName: "Tamara",
    lastName: "Williamson",
    displayName: "Tamara Williamson",
    nmls: "1933434",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "twilliamson@cliffcomortgage.com",
      directPhone: "516-350-5328",
      cellPhone: "718-490-7549",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=twilliamson%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    bio: "As a committed mortgage loan officer, I take pride in guiding clients through one of the most important financial decisions of their lives. My approach is rooted in dedication and a patient client-first mindset. I believe that every borrower deserves clarity, confidence, and a smooth experience, whether they're purchasing their first home, refinancing, or exploring new investment opportunities. I will take the time to understand each client's goals, explain every step of the process, and provide thoughtful solutions tailored to their unique needs. My mission is to make home financing feel approachable and stress free, ensuring that every client feels supported from application to closing.",
    hasPhoto: true,
  },
  {
    slug: "thomas-whalen",
    firstName: "Thomas",
    lastName: "Whalen",
    displayName: "Thomas Whalen",
    nmls: "9167",
    title: "Loan Officer",
    states: ["NY"],
    branchSlug: "uniondale-headquarters",
    links: {
      email: "twhalen@cliffcomortgage.com",
      directPhone: "516-456-4751",
      applyNow: "https://fastapp.cliffcomortgage.com/#/milestones?referrerId=twhalen%40cliffcomortgage.com&loanType=MORTGAGE",
    },
    bio: "Tom Whalen is a seasoned mortgage banker and insurance professional with 25 years of experience helping clients and referral partners make smart, confident financial decisions. Based in Bellmore, NY, Tom recently joined Cliffco Mortgage in Uniondale, bringing a relationship-first approach built through long-standing partnerships with real estate agents, who drive the majority of his referrals. Known for integrity and clear communication, he's also a certified continuing education (CE) instructor who teaches free monthly classes to local agents, strengthening connections and delivering real value.",
    hasPhoto: true,
  },
];

export const loanOfficersByBranch = (branchSlug: string): LoanOfficer[] =>
  LOAN_OFFICERS.filter((lo) => lo.branchSlug === branchSlug);

export const loanOfficersByState = (state: string): LoanOfficer[] =>
  LOAN_OFFICERS.filter((lo) => lo.states.includes(state));

export const loanOfficer = (slug: string): LoanOfficer | undefined =>
  LOAN_OFFICERS.find((lo) => lo.slug === slug);

export const loanOfficerSchemaPerson = (lo: LoanOfficer) => ({
  "@type": "Person",
  name: lo.displayName,
  jobTitle: lo.title,
  worksFor: { "@id": `${COMPANY.legalName}#organization` },
  identifier: {
    "@type": "PropertyValue",
    propertyID: "NMLS",
    value: lo.nmls,
  },
  sameAs: [nmlsConsumerAccessUrl(lo.nmls), lo.links?.linkedin].filter(Boolean),
  knowsLanguage: lo.languages,
  knowsAbout: lo.specialties,
});
