// @ts-check
import { defineConfig } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';
import vercel from '@astrojs/vercel';

// Deploy targets:
//  - DEPLOY_TARGET=pages → GitHub Pages preview at rafetangorra-tech.github.io/cliffco-site
//  - default            → production site at cliffcomortgage.com
const isPages = process.env.DEPLOY_TARGET === 'pages';

// https://astro.build/config
export default defineConfig({
  // Vercel adapter only for production — GitHub Pages preview uses static output
  ...(isPages ? {} : { adapter: vercel() }),
  site: isPages
    ? 'https://rafetangorra-tech.github.io'
    : 'https://cliffcomortgage.com',
  base: isPages ? '/cliffco-site' : '/',
  trailingSlash: 'always',
  redirects: {
    '/loans/fix-and-flip/': '/loans/business-bank-statement/',
    '/loan-officers/richard-alvarez/': '/loan-officers/',
    '/loan-officers/ralvarez/': '/loan-officers/',
    '/loan-officers/jose-cruz/': '/loan-officers/',
    '/loan-officers/jcruz/': '/loan-officers/',
    '/loan-officers/julia-jorge/': '/loan-officers/',
    '/loan-officers/jjorge/': '/loan-officers/',
    '/loan-officers/julia-jorge-delcarmen/': '/loan-officers/',
    '/loan-officers/adam-turkewitz/': '/loan-officers/',
    '/loan-officers/aturkewitz/': '/loan-officers/',
    '/loan-officers/samantha-roach/': '/loan-officers/',
    '/loan-officers/sroach/': '/loan-officers/',
    // --- Legacy WordPress URL map (from cliffco_sitemap_urls old.xlsx, validated against built routes) ---
    '/about-us/': '/about/',
    '/abroder/': '/loan-officers/adam-broder/',
    '/acarver/': '/loan-officers/andrea-carver/',
    '/accessibility-statement/': '/legal/accessibility/',
    '/affordability-calculator/': '/mortgage-guides/calculators/affordability/',
    '/all-open-positions/': '/careers/',
    '/astreet/': '/loan-officers/angelique-street/',
    '/azervas/': '/loan-officers/anastasios-zervas/',
    '/bkenney/': '/loan-officers/brandon-kenney/',
    '/blog/': '/mortgage-guides/blog/',
    '/bmcclarnon/': '/loan-officers/brendan-mcclarnon/',
    '/ccpa/': '/legal/ccpa/',
    '/cnguyen/': '/loan-officers/christian-nguyen/',
    '/condos-co-ops-condotels/': '/loans/condos-co-ops-condotels/',
    '/contact-us/': '/contact/',
    '/conventional-loans/': '/loans/conventional/',
    '/csoto/': '/loan-officers/christian-soto/',
    '/debbecke/': '/loan-officers/daniel-ebbecke/',
    '/dfallarino/': '/loan-officers/david-fallarino/',
    '/dfeliciano/': '/loan-officers/daphne-feliciano/',
    '/dhemberger/': '/loan-officers/donna-hemberger/',
    '/dillouz/': '/loan-officers/david-illouz/',
    '/dmizrahi/': '/loan-officers/david-mizrahi/',
    '/down-payment-assistance-programs/': '/mortgage-guides/down-payment-assistance-programs/',
    '/dscr-loans-real-estate-investors-guide/': '/mortgage-guides/dscr-loans-real-estate-investors-guide/',
    '/ecordeira/': '/loan-officers/emily-cordeira/',
    '/eestinvil/': '/loan-officers/emmanuel-estinvil/',
    '/emorais/': '/loan-officers/edward-morais/',
    '/emueller/': '/loan-officers/eric-mueller/',
    '/falosa/': '/loan-officers/fabrizio-alosa/',
    '/faqs/': '/mortgage-rates/',
    '/fha-loans/': '/loans/fha/',
    '/find-a-branch/': '/locations/',
    '/find-a-loan-officer/': '/loan-officers/',
    '/first-time-homebuyers/': '/first-time-homebuyer/',
    '/fort-lauderdale-fl/': '/locations/florida/fort-lauderdale/',
    '/fveras/': '/loan-officers/francisco-veras/',
    '/gdiamantakis/': '/loan-officers/george-diamantakis/',
    '/gjohansen/': '/loan-officers/gary-johansen/',
    '/glai/': '/loan-officers/gary-lai/',
    '/home/': '/',
    '/investors/': '/real-estate-investor-mortgage/',
    '/jamaica-ny/': '/locations/new-york/queens/',
    '/jamaya/': '/loan-officers/johana-amaya/',
    '/jborrero/': '/loan-officers/joshua-borrero/',
    '/jbrenner/': '/loan-officers/joshua-brenner/',
    '/jchen/': '/loan-officers/james-chen/',
    '/jcordeira/': '/loan-officers/joseph-cordeira/',
    '/jgiaquinto/': '/loan-officers/julian-giaquinto/',
    '/jhu/': '/loan-officers/justin-hu/',
    '/jperrone/': '/loan-officers/james-perrone/',
    '/jzucker/': '/loan-officers/jeannette-zucker/',
    '/kadler/': '/loan-officers/kathie-adler/',
    '/karabian/': '/loan-officers/kyle-arabian/',
    '/kcruz/': '/loan-officers/keyla-cruz/',
    '/kdaniel/': '/loan-officers/kendra-daniel/',
    '/kscott/': '/loan-officers/kevan-scott/',
    '/larisa-zambelli/': '/loan-officers/larisa-zambelli/',
    '/lauren-zambelli/': '/loan-officers/lauren-zambelli/',
    '/lhartman/': '/loan-officers/lisa-hartman/',
    '/lhoren/': '/loan-officers/lee-horen/',
    '/lisa-zambelli/': '/loan-officers/lisa-zambelli/',
    '/llevy/': '/loan-officers/logan-levy/',
    '/margenzio/': '/loan-officers/mario-argenzio/',
    '/maziz/': '/loan-officers/michael-aziz/',
    '/mbisbee/': '/loan-officers/michael-bisbee/',
    '/mortgage-glossary/': '/mortgage-guides/glossary/',
    '/mpatterson/': '/loan-officers/mitchell-patterson/',
    '/myoussef/': '/loan-officers/moses-youssef/',
    '/ngeyer/': '/loan-officers/nadia-geyer/',
    '/non-qm-loans/': '/loans/non-qm-self-employed/',
    '/non-qm-loans-guide/': '/mortgage-guides/non-qm-loans-guide/',
    '/non-qm-mortgage-self-employed/': '/mortgage-guides/non-qm-mortgage-self-employed/',
    '/orlando-fl/': '/locations/florida/orlando/',
    '/pmontesano/': '/loan-officers/paul-montesano/',
    '/privacy-policy/': '/legal/privacy/',
    '/products/': '/loans/',
    '/purchase-clients/': '/purchasing-refinancing/',
    '/qduong/': '/loan-officers/queeny-duong/',
    '/rappo/': '/loan-officers/renald-appo/',
    '/refinancing/': '/loans/refinancing/',
    '/renovation-loan/': '/loans/renovation/',
    '/reverse-mortgage-guide/': '/mortgage-guides/reverse-mortgage-guide/',
    '/reverse-mortgages/': '/reverse-mortgage/',
    '/rgarcia/': '/loan-officers/raymond-garcia/',
    '/rriddle/': '/loan-officers/ryan-riddle/',
    '/rrojas/': '/loan-officers/rafael-rojas/',
    '/self-employed/': '/self-employed-mortgage/',
    '/seniors/': '/reverse-mortgage/',
    '/shasib/': '/loan-officers/syed-hasib/',
    '/skhan/': '/loan-officers/shahraj-khan/',
    '/slazo/': '/loan-officers/steve-lazo/',
    '/small-business/': '/self-employed-mortgage/',
    '/srivera/': '/loan-officers/steven-rivera/',
    '/twhalen/': '/loan-officers/thomas-whalen/',
    '/twilliamson/': '/loan-officers/tamara-williamson/',
    '/usda-loans/': '/loans/usda/',
    '/va-loans/': '/loans/va/',
    '/what-is-an-investment-mortgage/': '/mortgage-guides/what-is-an-investment-mortgage/',
    '/wromero/': '/loan-officers/wenceslao-romero/',
    '/buydown-calculator/': '/mortgage-guides/calculators/buydown/',
    '/closing-costs/': '/mortgage-guides/calculators/closing-costs/',
    '/jmarrero/': '/loan-officers/',
    // Old audience landing pages with no direct equivalent - nearest match
    '/service-members/': '/loans/va/',
    '/rural-residents/': '/loans/usda/',
    '/freelance/': '/mortgages-for-freelancers-entrepreneurs-investors/',
    '/non-us-citizens/': '/loans/itin-mortgage/',
    '/tech/': '/complex-income-mortgage-solutions/',
    '/salon/': '/self-employed-mortgage/',
    '/trade-workers/': '/self-employed-mortgage/',
    '/real-estate-agents/': '/self-employed-mortgage/',
    '/healthcare-professionals/': '/purchasing-refinancing/',
  },

  vite: {
    plugins: [tailwindcss()],
    server: {
      fs: {
        allow: ['..'],
      },
    },
  },

  integrations: [sitemap()],

  build: {
    inlineStylesheets: 'auto',
  },
});